### ISSUE TITLE
Errors fetching movie metadata 

### ISSUE THREAD

**Issue by seanegoodwin** [ZeroQI/Hama.bundle#99] opened 2016-12-10 06:33 UTC
I've recently updated my version of Hama (the previous version would've been from August or September) and I've noticed that I'm not able to get metadata for movies using the HamaMovies scanner. This seems to be reproducible on all of my movies, but this one in particular was caused by Little Witch Academia (I don't think this actually matters). 

Here's what I think are the relevant logs, please let me know if you need more.
```

2016-12-10 01:24:03,379 - com.plexapp.agents.hama (80870c000) : ERROR (networking/load:219) - Error opening URL 'http://api.tmdb.org/3/find/?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&external_source=imdb_id'
2016-12-10 01:24:03,379 - com.plexapp.agents.hama (80870c000) : ERROR (__init__/get_json:909) - Error fetching JSON url: 'http://api.tmdb.org/3/find/?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&external_source=imdb_id', Exception: 'HTTP Error 404: Not Found'
2016-12-10 01:24:03,379 - com.plexapp.agents.hama (80870c000) : ERROR (__init__/Update:708) - get_json - Error fetching JSON page 'http://api.tmdb.org/3/find/?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&external_source=imdb_id', Exception: ''NoneType' object has no attribute '__getitem__''
2016-12-10 01:24:03,379 - com.plexapp.agents.hama (80870c000) : INFO (__init__/Update:708) - TVDB - tvdbid: '259863', url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/259863/all/en.xml'
2016-12-10 01:24:03,379 - com.plexapp.agents.hama (80870c000) : INFO (__init__/xmlElementFromFile:913) - url: 'http://thetvdb.com/api/A27AD9BE0DA63333/series/259863/all/en.xml', filename: 'TVDB/259863.xml'
2016-12-10 01:24:03,384 - com.plexapp.agents.hama (80870c000) : DEBUG (networking/load:161) - Fetching 'http://thetvdb.com/api/A27AD9BE0DA63333/series/259863/all/en.xml' from the HTTP cache
2016-12-10 01:24:03,391 - com.plexapp.agents.hama (80870c000) : CRITICAL (agentkit/_update:1067) - Exception in the update function of agent named 'HamaMovies', called with guid 'com.plexapp.agents.hama://anidb-9250?lang=en' (most recent call last):
  File "/usr/pbi/plexmediaserver-amd64/share/plexmediaserver/Resources/Plug-ins-1bef33a/Framework.bundle/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 976, in update
    def update(self, metadata, media, lang, force ): self.Update(metadata, media, lang, force,  True )
  File "/var/db/plexdata/Plex Media Server/Plug-ins/Hama.bundle/Contents/Code/__init__.py", line 708, in Update
    elif not movie and (len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1):  keys = ["tvdbid: %s"  % (WEB_LINK % (TVDB_SERIE_URL  % tvdbid,  tvdbid) )]
AttributeError: 'MediaTree' object has no attribute 'seasons'

```

**Comment by KingJ** [comment] 2016-12-10 10:48
I've confirmed this issue, specifically when scanning Little Witch Academia. It looks like LWA has an entry on TVDB for an upcoming series, so Hama attempts to pull metadata for it even though we're in movie mode. Fix incoming.

**Comment by ZeroQI** [comment] 2016-12-11 12:40
i hardly use in movie mode since i put movies and series in the same series library so movie specific errors pops from time to time....
Thetvdb is the main backdrop, poster and also used for summaries in other languages.
If we prevent movies to use Tvdb meta at all we are getting bad size low quality posters on all movies and i cannot validate that since most anidb posters sucks, there is no visual consistency and sub par res for many......

we need just the test to prevent: 'MediaTree' object has no attribute 'seasons' if you do add the test on line 295 the tv theme works...

here is a fix for this specific error i believe: elif not movie and hasattr(MediaTree, 'seasons') and (len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1):

I need to make sure there is no other errors popping up though

**Comment by KingJ** [comment] 2016-12-11 15:28
I've moved the test from L270 to L295 as suggested. Tested it out locally and the right information is now being pulled from TVDB (fanart, posters etc) without crashing. I've pushed it in to PR #100 and the new commit supersedes the old one.

**Comment by KingJ** [comment] 2016-12-11 15:33
As an aside, LWA is an interesting little edge case - AniDB has it listed as a movie, but the related entry on TVDB is [S03E03 of the Anime Mirai Project](http://www.thetvdb.com/?tab=episode&seriesid=259863&seasonid=496703&id=4362126&lid=14) - which let it pass the `defaulttvdbseason != "0"` check on L295.

Interestingly, TVDB also has it listed as a [special of the upcoming LWA series](http://www.thetvdb.com/?tab=episode&seriesid=318161&seasonid=684016&id=5784980&lid=7).

**Comment by sven-7** [comment] 2016-12-11 15:35
That's pretty common with TVDB, IMO. I see it a lot. They often will put movies as specials on series.

**Closed** 2016-12-11 16:54 UTC
