### ISSUE TITLE
OVA/Movie titles are incorrectly labeled when it's processed in TV Shows section

### ISSUE THREAD

**Issue by plato79** [ZeroQI/Hama.bundle#504] opened 2022-02-13 08:16 UTC
Well, the problem is when I add an OVA it does actually find it, and almost everything is correct..

But when you go to the file itself, it's labeled as episode 1 of the series.

Example:

Here is one of the OVA of the KonoSuba and how Hama labeled it:  

```
Kono Subarashii Sekai ni Shukufuku o! Kurenai Densetsu
2019
A video game-loving shut-in, Satou Kazuma's life should've ended when he was hit by a truck, but through a twist of fate, he ends up reincarnating in another world--and dragging the troublemaking goddess, Aqua, the wildly dorky mage, Megumin, and the unrelentingly delusional lady knight, Darkness, with him.

Now, the Crimson Demon village that Megumin and Yun'yun are from is facing a threat that could mean its ending. Kazuma and his gang follow Yun'yun, who returns to the Crimson Demon village intent on saving it... when they are faced with their greatest threat yet! What will become of the unremarkable adventurer Kazuma's life in another world?!

```

Everything looks great doesn't it? But when you check the file itself which shows as S1 E1:

```
[Kono Subarashii Sekai ni Shukufuku o! Kurenai Densetsu]
[Season 1]
Episode 1·This Self-Proclaimed Goddess and Reincarnation in Another World!
89 min
TV-14
76%
Gamer Kazuma dies in a freak accident, and is met in the afterlife by a crass goddess, Aqua.
DIRECTED BY
[Kanasaki Takaomi]
WRITTEN BY
[Akatsuki Natsume]
RELEASED
August 30, 2019
VIDEO
1080p (HEVC Main 10)
AUDIO
Japanese (OPUS Stereo)
SUBTITLES

```

As you can see it's actually the first episode of the series.. 

I think the problem lies with how OVA is realized when it's used in TV section. It finds the file and assigns a season and episode number. I know you'll probably say, then use it in another library with Movie selected. But then I don't think Plex could realize that the OVA is also in the collection.

I prefer watching an anime in order and use collections for this. Checking anidb to see what's after that is cripples the intent.

Is there a possibility that if OVA / Movie is one episode it will fill episode file with the main entry?

**Comment by ZeroQI** [comment] 2022-02-13 12:38
Movies in tv libraries will be seen as s01e01.
It actually allow movie and series collections I believe, to be confirmed.
It is meant to use series description for episode summary depending many factord, but I don't know the library set language and episode and series summaries settings as the per series agent log was not attached...

**Comment by plato79** [comment] 2022-02-13 16:38
Hmm, the collection you mentioned is a manual collection right? Not that Plex builds this one itself? If it's automatic then maybe it's better if I move my Anime OVAs and Movies in another directory and create a new library assigned as a movie and assign HamaMovies as agent.

I checked a few anime movies and mostly they're correct. But for example when I checked Violet Evergarden Movie, it is in the same situation ( the episode summary is actually from the series' first episode ).

I'm not sure what you want to try to explain here:

> - https://anidb.net/anime/13310 "Kono Subarashii Sekai ni Shukufuku o! Kurenai Densetsu" is a Movie.
> - Series/Episodes summary default source order: "TheTVDB, AniDB"
> - Series/Episodes title default source order: "AniDB, TheTVDB | TheTVDB, AniDB"

I set HamaTV as agent to my Anime library and that's it. I checked the orders in the library properties for HamaTV agent, and everything is AniDB first. Do I need to set this ordering on somewhere else?

What kind of log do you need to check the situation?

**Comment by ZeroQI** [comment] 2022-02-13 16:52
Readme toubleshooting section has the path to the logs...

**Comment by plato79** [comment] 2022-02-13 17:03
@ZeroQI No, I meant which log do you need.. I know where the logs are stored.

**Comment by ZeroQI** [comment] 2022-02-13 17:29
We are troubleshooting sereis in a tv sereis library, for which the season/ep number is correst, so the custom per-series log from Hama in agent data folders

**Comment by plato79** [comment] 2022-02-13 18:25
I found files like: 'Violet Evergarden [anidb-12138].agent-update.log' etc..

But the thing is 'Violet Evergarden [anidb-12138]' is the series' folder. The movie is in the root directory of the media folder. 
I found '..agent-update.log' has entries about the movie.. I hope this is what you asked about.
[agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/8056337/agent-update.log)

**Comment by ZeroQI** [comment] 2022-02-13 18:31
That's the one. It explain at the end where each field data comes from
- series summary from anidb
- episode summary from thetvdb after failing to get it from anidb

**Comment by plato79** [comment] 2022-02-13 20:30
Does it fail because there are no episodes for a movie? Then, it should match anidb id with thetvdb id... Why does it get episode summary from the series to the movie's episode summary? Is there a matching error?

**Comment by plato79** [comment] 2022-02-13 20:36
Uh.. So answering my own question.. It seems it matches to series instead of the movie..  It should match to "133610", but instead it matches to "330139"

**Comment by natyusha** [comment] 2022-02-14 20:18
If you look at `Kono Subarashii Sekai ni Shukufuku wo! Kurenai Densetsu.agent-update.log` you will see in the `TheTVDB.GetMetadata()` section that the correct information is there but is marked for `abs_number: 0` and doesn't get used.

```
--- episodes ------------------------------------------------------------------------------------------------------------------------------------------------
common.LoadFile() - File cached locally - Filename: 'TheTVDB\json\303867\episodes_page1_en.json', Age: '0.05 days', Limit: '6 days', url: 'https://api.thetvdb.com/series/303867/episodes?page=1'
[ ]    s0e3 s01e0-1 anidbid:         air_date: 2016-06-24
[ ]    s0e4 s01e000 anidbid:         air_date: 2017-07-24
[X]    s0e5 s01e001 anidbid:   13310 air_date: 2019-08-30 abs_number: 0, title: Movie: Legend of Crimson
 - [1] title:   [en] Movie: Legend of Crimson
 - [1] summary: [en] It is not strange that the Demon Lord's forces fear the Crimson Demons, the clan from which Megumin and Yunyun originate. Even if the Demon Lord's generals attack their village, the Crimson Demons can just easily brush them off with their supreme mastery of advanced and overpowered magic. When Yunyun receives a seemingly serious letter regarding a potential disaster coming to her hometown, she immediately informs Kazuma Satou and the rest of his party. After a series of wacky misunderstandings, it turns out to be a mere prank by her fellow demon who wants to be an author. Even so, Megumin becomes worried about her family and sets out toward the Crimson Demons' village with the gang. There, Kazuma and the others decide to sightsee the wonders of Megumin's birthplace. However, they soon come to realize t
[Kono Subarashii Sekai ni Shukufuku wo! Kurenai Densetsu.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/8063664/Kono.Subarashii.Sekai.ni.Shukufuku.wo.Kurenai.Densetsu.agent-update.log)
hat the nonsense threat they received might have been more than just a joke.
common.LoadFile() - File cached locally - Filename: 'TheTVDB\json\303867\episode_7055302_ja.json', Age: '0.05 days', Limit: '6 days', url: 'https://api.thetvdb.com/episodes/7055302'
 - [ ] thumb: https://thetvdb.plexapp.com/banners/series/303867/episodes/62082788.jpg
[X]    s1e1 s01e001 anidbid: xxxxxxx air_date: 2016-01-14 abs_number: 1, title: This Self-Proclaimed Goddess and Reincarnation in Another World!
 - [1] title:   [en] This Self-Proclaimed Goddess and Reincarnation in Another World!
 - [1] summary: [en] Gamer Kazuma dies in a freak accident, and is met in the afterlife by a crass goddess, Aqua.
common.LoadFile() - File cached locally - Filename: 'TheTVDB\json\303867\episode_5427421_ja.json', Age: '0.05 days', Limit: '6 days', url: 'https://api.thetvdb.com/episodes/5427421'
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/303867/5427421.jpg
 ```
 
 Attached a full log for the series since you seem to be missing yours.

**Comment by ZeroQI** [comment] 2022-03-12 10:34
File: M:\Anime\Kono Subarashii Sekai ni Shukufuku wo! Kurenai Densetsu\Kono Subarashii Sekai ni Shukufuku wo! Kurenai Densetsu.mkv [good naming convention]
Matched to: anidb-13310 [correct]

Each field is different and have different order for the metadata sources if you take a look at the agent settings in plex [gear icon]. I do not reproduce issues, as i do not use Hama and do not use Plex anymore since quite a few years, so expect logs even if issue is reproductible

Anidb s1e1 =>tvdb s00e05 (default tvdb season 0, offset 4 added to ep 1=5)

common.LoadFile() - File cached locally - Filename: 'TheTVDB\json\303867\episodes_page1_en.json', Age: '0.05 days', Limit: '6 days', url: 'https://api.thetvdb.com/series/303867/episodes?page=1'
[X]    s0e5 s01e001 anidbid:   13310 air_date: 2019-08-30 abs_number: 0, title: Movie: Legend of Crimson
 - [1] title:   [en] Movie: Legend of Crimson
 - [1] summary: [en] It is not strange that the Demon Lord's forces fear the Crimson Demons, the clan from which Megumin and Yunyun originate. Even if the Demon Lord's generals attack their village, the Crimson Demons can just easily brush them off with their supreme mastery of advanced and overpowered magic. When Yunyun receives a seemingly serious letter regarding a potential disaster coming to her hometown, she immediately informs Kazuma Satou and the rest of his party. After a series of wacky misunderstandings, it turns out to be a mere prank by her fellow demon who wants to be an author. Even so, Megumin becomes worried about her family and sets out toward the Crimson Demons' village with the gang. There, Kazuma and the others decide to sightsee the wonders of Megumin's birthplace. However, they soon come to realize that the nonsense threat they received might have been more than just a joke.
common.LoadFile() - File cached locally - Filename: 'TheTVDB\json\303867\episode_7055302_ja.json', Age: '0.05 days', Limit: '6 days', url: 'https://api.thetvdb.com/episodes/7055302'
 - [ ] thumb: https://thetvdb.plexapp.com/banners/series/303867/episodes/62082788.jpg
[X]    s1e1 s01e001 anidbid: xxxxxxx air_date: 2016-01-14 abs_number: 1, title: This Self-Proclaimed Goddess and Reincarnation in Another World!
 - [1] title:   [en] This Self-Proclaimed Goddess and Reincarnation in Another World!
 - [1] summary: [en] Gamer Kazuma dies in a freak accident, and is met in the afterlife by a crass goddess, Aqua.

Your issue is that the mapping assign 2 tvdb eps to s01e-001, already mentionned on 
- https://github.com/ZeroQI/Hama.bundle/issues/490
- https://github.com/ZeroQI/Hama.bundle/issues/500

Closing this as duplicate of:
- https://github.com/ZeroQI/Hama.bundle/issues/500
- https://github.com/ZeroQI/Hama.bundle/issues/504

Will keep 500 which has better description and pinpointed the change that broke it

**Closed by ZeroQI** 2022-03-12 10:34 UTC
Labels: No logs
