### ISSUE TITLE
Poster art is not pulling for the correct show

### ISSUE THREAD

**Issue by rcdailey** [ZeroQI/Hama.bundle#220] opened 2018-06-20 01:53 UTC
I'm opening an issue because I *suspect* this may be a bug, but mostly because the Plex discussion forums are in read-only mode until June 21st, 2018. I apologize in advance, since I'm technically abusing this issue to also get support from you until that time. If you're OK with this, I'm happy to close this issue when the forums are writable again, assuming we don't ultimately conclude a real bug needs to be addressed.

This is a continuation of our discussion on the Plex forums, where your last reply was [here](https://forums.plex.tv/discussion/comment/1686888/#Comment_1686888). I tried the XML you suggested, and I reordered my agent settings for Hama as follows:

* summary: `AniDB, TheTVDB | TheTVDB, AniDB`
* poster: `AniDB, TheTVDB, tvdb4, TheMovieDb, FanartTV`

The summary definitely is pulling from anidb now instead of tvdb, but the poster is still wrong. I don't care where the poster comes from (I think it's coming from tvdb right now), but it's a poster for the wrong show. Is it even possible to get the right poster for this show? I know this series & the movies are really weird...

Here is a screenshot of the poster I get:

![image](https://user-images.githubusercontent.com/1768054/41633049-727ffc42-7402-11e8-8a29-9925cb427487.png)

Also the posters for the episodes should be from TVDB (or at least, I expect them to be) after your XML changes, but I do not see the correct posters in use. Actual posters in plex:

![image](https://user-images.githubusercontent.com/1768054/41633073-8deafa9a-7402-11e8-9b19-3f7c8f7b448a.png)

Posters I see in tvdb, such as [for the first movie](https://www.thetvdb.com/series/monogatari/episodes/4139150), are not appearing in Plex.

Are my expectations wrong here? What is the behavior you personally would expect here?

Thanks again, and I apologize in advance for opening a discussion here.

Logs are here: [logs.txt](https://github.com/ZeroQI/Hama.bundle/files/2117501/logs.txt)

**Comment by ZeroQI** [comment] 2018-06-20 05:01
" I don't care where the poster comes from (I think it's coming from tvdb right now), but it's a poster for the wrong show. "

Prefs[EpisodeLanguagePriority] = en, x-jat, ja                                                  (Default: x-jat, en, ja)
Prefs[SerieLanguagePriority     ] = en, x-jat, ja                                                  (Default: x-jat, en, ja)
Prefs[posters                             ] = AniDB, TheTVDB, tvdb4, TheMovieDb, FanartTV
                    (Default: tvdb4, TheTVDB, TheMovieDb, FanartTV, AniDB)
```
2018-06-19 20:41:46,845 (8dc) :  INFO (logkit:16) - [=] posters                  ( 1)  Sources: (AniDB), TheTVDB, tvdb4, TheMovieDb, FanartTV                 Inside: '['FanartTV', 'TheTVDB', 'AniDB', 'TheMovieDb']'  Value: '{'http://img7.anidb.net/pics/anime/178226.jpg': (u'AniDB\\poster\\178226.jpg', 99, 'http://img7.anidb.net/pics/anime/thumbs/150/178226.jpg-thumb.jpg')}'
2018-06-19 20:41:46,846 (8dc) :  INFO (logkit:16) - [=] posters                  (20)  Sources: AniDB, (TheTVDB), tvdb4, TheMovieDb, FanartTV                 Inside: '['FanartTV', 'TheTVDB', 'AniDB', 'TheMovieDb']'  Value: '{u'https://thetvdb.plexapp.com/banners/posters/102261-9.jpg': (u'TheTVDB/posters/102261-9.jpg', 11, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-9.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-26.jpg': (u'TheTVDB/posters/102261-26.jpg', 20, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-26.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-10.jpg': (u'TheTVDB/posters/102261-10.jpg', 10, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-10.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-13.jpg': (u'TheTVDB/posters/102261-13.jpg', 14, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-13.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-11.jpg': (u'TheTVDB/posters/102261-11.jpg', 12, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-11.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-12.jpg': (u'TheTVDB/posters/102261-12.jpg', 13, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-12.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-1.jpg': (u'TheTVDB/posters/102261-1.jpg', 1, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-1.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-3.jpg': (u'TheTVDB/posters/102261-3.jpg', 5, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-3.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-5.jpg': (u'TheTVDB/posters/102261-5.jpg', 4, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-5.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-7.jpg': (u'TheTVDB/posters/102261-7.jpg', 8, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-7.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-4.jpg': (u'TheTVDB/posters/102261-4.jpg', 6, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-4.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-6.jpg': (u'TheTVDB/posters/102261-6.jpg', 7, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-6.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-8.jpg': (u'TheTVDB/posters/102261-8.jpg', 9, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-8.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-23.jpg': (u'TheTVDB/posters/102261-23.jpg', 19, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-23.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-17.jpg': (u'TheTVDB/posters/102261-17.jpg', 21, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-17.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-19.jpg': (u'TheTVDB/posters/102261-19.jpg', 17, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-19.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-15.jpg': (u'TheTVDB/posters/102261-15.jpg', 15, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-15.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-18.jpg': (u'TheTVDB/posters/102261-18.jpg', 16, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-18.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-20.jpg': (u'TheTVDB/posters/102261-20.jpg', 18, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-20.jpg'), u'https://thetvdb.plexapp.com/banners/posters/102261-2.jpg': (u'TheTVDB/posters/102261-2.jpg', 3, u'https://thetvdb.plexapp.com/banners/_cache/posters/102261-2.jpg')}'
2018-06-19 20:41:46,848 (8dc) :  INFO (logkit:16) - [=] posters                  ( 1)  Sources: AniDB, TheTVDB, tvdb4, (TheMovieDb), FanartTV                 Inside: '['FanartTV', 'TheTVDB', 'AniDB', 'TheMovieDb']'  Value: '{u'http://image.tmdb.org/t/p/original/fnwflZCpqKjUSsI15R1opaNQ0ZJ.jpg': (u'TheMovieDb\\poster\\fnwflZCpqKjUSsI15R1opaNQ0ZJ.jpg', 90, None)}'
2018-06-19 20:41:46,848 (8dc) :  INFO (logkit:16) - [=] posters                  ( 5)  Sources: AniDB, TheTVDB, tvdb4, TheMovieDb, (FanartTV)                 Inside: '['FanartTV', 'TheTVDB', 'AniDB', 'TheMovieDb']'  Value: '{u'https://assets.fanart.tv/fanart/tv/102261/tvposter/bakemonogatari-53b6e3dadc230.jpg': ('FanartTV/tv/102261102261/tvposter/41649.jpg', 100, None), u'https://assets.fanart.tv/fanart/tv/102261/tvposter/bakemonogatari-53b6e3a846fe8.jpg': ('FanartTV/tv/102261102261/tvposter/41648.jpg', 100, None), u'https://assets.fanart.tv/fanart/tv/102261/tvposter/bakemonogatari-53b6e40244ee9.jpg': ('FanartTV/tv/102261102261/tvposter/41650.jpg', 100, None), u'https://assets.fanart.tv/fanart/tv/102261/tvposter/bakemonogatari-5636087c590bd.jpg': ('FanartTV/tv/102261102261/tvposter/58019.jpg', 100, None), u'https://assets.fanart.tv/fanart/tv/102261/tvposter/bakemonogatari-53b6e41f1572c.jpg': ('FanartTV/
tv/102261102261/tvposter/41651.jpg', 100, None)}'
```

AniDB poster is downloaded but at index 99 so lowest priority.
- http://img7.anidb.net/pics/anime/178226.jpg
- http://img7.anidb.net/pics/anime/thumbs/150/178226.jpg-thumb.jpg

according to ScudLee's AnimeLists ep 1-3 anidb = season 0 ep 2,19-20 so correct
https://www.thetvdb.com/series/monogatari/seasons/0

no screenshot given in logs ('thumbs' not present) so the 'wrong' episode thumbnail is not from that run of the agent, probably kept from prior tests or taken from file. 

Errors found:
- Priority 3 - poster priority not implemented, AniDB is 99. workaround: edit the series and click on AniDB poster that is last normally.
- Priority 1 - mapping list missing tvdb ep mapping despite being present in file, so no matching anidb/thetvdb

**Comment by rcdailey** [comment] 2018-06-20 22:56
Sorry if I've missed some important answers to my questions, but it looks like you are just taking notes here. You mentioned various prefs at the top. Are those just notes to yourself or are you pointing out incorrect configuration on my part? I also do not understand the priorities, is there something I need to do to fix them? Or are you saying it's a bug to be fixed?

**Comment by ZeroQI** [comment] 2018-06-21 05:35
i am explaining ot trying to explain the logic. in short i have to solve 2 bugs in the code:
- Priority 3 - poster priority not implemented, AniDB is 99. workaround: edit the series and click on AniDB poster that is last normally.
- Priority 1 - mapping list missing tvdb ep mapping despite being present in file, so no matching anidb/thetvdb

**Comment by ZeroQI** [comment] 2018-06-22 08:03
reproduced
no thumb actually given by agent for all 3 eps, working on it

**Comment by rcdailey** [comment] 2018-06-22 11:36
Sorry I just realized I forgot to attach logs last night. I'll attach them here anyway, even though you were able to reproduce: 
[logs.txt](https://github.com/ZeroQI/Hama.bundle/files/2127449/logs.txt)

**Comment by rcdailey** [comment] 2018-06-23 04:37
Tested with your new commit, I didn't notice any changes. Brand new logs: 
[logs.txt](https://github.com/ZeroQI/Hama.bundle/files/2129639/logs.txt)

**Comment by ZeroQI** [comment] 2018-06-23 04:59
poster once in the database won't change id however.
could wipe all posters everytime, seem overkill
rank id 1 so anidb poster by default with your settings
- [=] posters                  ( 1)  Sources: (AniDB), TheTVDB, tvdb4, TheMovieDb, FanartTV                 Inside: '['FanartTV', 'TheTVDB', 'AniDB', 'TheMovieDb']'  Value: '{'http://img7.anidb.net/pics/anime/178226.jpg': (u'AniDB\\poster\\178226.jpg', 1, 'http://img7.anidb.net/pics/anime/thumbs/150/178226.jpg-thumb.jpg')}'

Although get ep thumbs correct as well
![capture](https://user-images.githubusercontent.com/5163877/41805949-7e27534c-76aa-11e8-90dd-1f66600c77b5.PNG)

**Comment by rcdailey** [comment] 2018-06-23 05:14
Is there an easy way to force a refresh? I am just using the refresh
Metadata option in the episode menu in plex

**Comment by ZeroQI** [comment] 2018-06-23 07:41
Trying but metadata.posters[url] = string containing the poster file content itself, cannot see way to access poster rank
i can use validate_keys(valid_names) to remove no longer valid files, could work for episode thumbs (screenshots) but posters are tricky.

Uploaded new version, poster won't change but ep previews (thumbs field in plex) should update

**Comment by rcdailey** [comment] 2018-06-23 13:54
Is the Metadata object one of your own objects? If so you could change
posters to be a nested object with content plus rank inside

**Comment by ZeroQI** [comment] 2018-06-23 14:17
it is Plex metadata object and structure received by the update() function:

`def Update(metadata, media, lang, force, movie)`

Please update to the latest code, and report, it should update the episode 'thumbs' field, it did for me.
For the poster i am thinking about solutions. It already works if re-creating the library as the poster rank id is good now IF the poster wasn't already assigned to the series, so just select manualy AniDB poster for that one, new series you add won't have the issue

**Comment by rcdailey** [comment] 2018-06-23 18:56
I still think it would be good to have posters update and redownload if needed, especially since poster art can be updated on the websites and I would want my library to pull down those changes when I refresh metadata. But I agree this is just a polish step, and isn't absolutely required, but probably worth putting on your backlog for when you have bandwidth for it.

As far as testing does, I updated latest and again I see no poster updates (for series OR episodes). New logs here: 
[logs.txt](https://github.com/ZeroQI/Hama.bundle/files/2130146/logs.txt)

And screenshot for completeness:

![image](https://user-images.githubusercontent.com/1768054/41812694-2cc7ceee-76ed-11e8-86c6-0864f97d4277.png)

**Comment by KurtzPT** [comment] 2018-06-23 19:22
I'm going to post this here, since it's a similar show and it's about the episode thumbs, that are not correct.

The files/show are the following:

> Nekomonogatari (Kuro) Tsubasa Family [anidb-9453]/Nekomonogatari.(Black).-.02.[SUB.1080p.BluRay.x264].[10bit].[DHD].mkv
Nekomonogatari (Kuro) Tsubasa Family [anidb-9453]/Nekomonogatari.(Black).-.03.[SUB.1080p.BluRay.x264].[10bit].[DHD].mkv
Nekomonogatari (Kuro) Tsubasa Family [anidb-9453]/Nekomonogatari.(Black).-.04.[SUB.1080p.BluRay.x264].[10bit].[DHD].mkv
Nekomonogatari (Kuro) Tsubasa Family [anidb-9453]/Nekomonogatari.(Black).-.05.[SUB.1080p.BluRay.x264].[10bit].[DHD].mkv

**AniDB Link:** http://anidb.net/perl-bin/animedb.pl?show=anime&aid=9453
AnimeList mapping:
`    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-3;2-4;3-5;4-6;</mapping>
    </mapping-list>`
**TVDB Link:** https://www.thetvdb.com/series/monogatari/seasons/0

So from the above information, the correct mapping from the 4 files are from episode 3 to episode 6 on season 0 (TVDB)

> 3 | Tsubasa Family - Part 1
4 | Tsubasa Family - Part 2 
5 | Tsubasa Family - Part 3
6 | Tsubasa Family - Part 4

Thumbs that Hama downloaded:
![image](https://user-images.githubusercontent.com/14930057/41812802-e3c10e1a-7721-11e8-8d81-c928a924be9b.png)

You can check on TVDB that all thumbs are in the wrong order, and the last one isn't even a correct thumb.
Log: [Nekomonogatari (Kuro) Tsubasa Family [anidb-9453].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2130165/Nekomonogatari.Kuro.Tsubasa.Family.anidb-9453.agent-update.log)

The first 3 thumbs are downloaded but in the wrong order, and the last thumb isn't downloaded at all.

**Comment by KurtzPT** [comment] 2018-06-23 20:02
I'm adding an anime of this same series (Nekomonogatari (Kuro) Tsubasa Family [anidb-9453]).

This series maps to season 0 of https://www.thetvdb.com/series/monogatari/.

The anime posters are getting downloaded, I don't find any problem with it, but the season posters are not being downloaded.

TVDB season posters: https://www.thetvdb.com/series/monogatari/seasons/0/artwork/season

Plex season posters downloaded: 
![image](https://user-images.githubusercontent.com/14930057/41813182-afacb73a-7728-11e8-87fd-afce54799a14.png)

Note that, all those posters are from season 1 in TVDB, so it's getting all season posters from the wrong season.

**Comment by KurtzPT** [comment] 2018-06-28 10:03
@ZeroQI In my opinion, it should download all posters for season 0, it's the same behavior for the other seasons I think (at least for season 1)

**Comment by ZeroQI** [comment] 2018-06-28 20:51
@KurtzPT the more i look into it the blurier it gets as there is series posters and season posters i get from TheTVDB...

You are saying i should in this situation hama should load TheTVDB season 0 only posters (might include the season 0 or specials wording) for both the series poster and season poster, and preferably not the same one?

**Comment by KurtzPT** [comment] 2018-06-28 21:59
Maybe an image is best to not create any confusion, since my last image might be confusing (since I have plex to hide single seasons)

![image](https://user-images.githubusercontent.com/14930057/42062598-f0cd72f8-7b25-11e8-85ea-0c1f0de9ee57.png)

- **Serie Posters** are all being downloaded correctly, using the languages in the preferences. Only Serie Posters are in here.
- **Season Posters**, are only applied in the season "itens" inside the red rectangular.  In this case, Hama should **ONLY** get the Season Posters here and **NOT** any of the Serie Posters.

**Making it short:**

- Both Special and Season 0 wordings, should **only** download all posters on TVDB inside the Season 0.
- Season X ( X is a number >0 ) should **only** download all posters on TVDB inside the Season X
- Serie Posters stays the same as it is.

**Comment by rcdailey** [comment] 2018-06-28 22:10
The short of my expectations is that series, season, and episode posters
are all obtained from TVDB when using non-absolute numbering (e.g. S01E01).
Ultimately this is the difficulty I had with the Kizumonogatari movie in
episode format.

**Comment by KurtzPT** [comment] 2018-06-28 22:54
@rcdailey I understand why you want all posters in the serie posters section on Plex, for your case it would have the correct version of the poster in that movie. It's actually something I didn't really think about it since I usually just manually correct these, because well tvdb sucks and sometimes don't even have posters on the seasons section.

**Comment by KurtzPT** [comment] 2018-06-30 20:35
With a new library and the new version:

- Season 0 posters are being downloaded now into the season posters:
![image](https://user-images.githubusercontent.com/14930057/42128838-90640264-7cac-11e8-9a5b-15038e6cdb75.png)
Unfortunately it seems its getting the all the season 1 posters into season 0 posters too, which I think it shouldn't be getting.

- It's downloading season 0 posters into the serie posters, which I think it's fine since my example only has season 0 episodes, I would have to try with more episodes from other seasons.

- It's getting the wrong thumb for episode 2 (this is mapped to episode s00e03 on TVDB)
![image](https://user-images.githubusercontent.com/14930057/42128883-7a6a5aca-7cad-11e8-8e44-35fec44b76c5.png)

**Comment by ZeroQI** [comment] 2018-07-03 07:55
@KurtzPT 
- posters solved but not uploaded yet
- both anidb s00e02 and s00e03 gets mapped to anidb s01e02 that's tricky
wip

**Comment by KurtzPT** [comment] 2018-07-03 08:42
@ZeroQI can't Hama just read the AnimeList mappings? This was working like 2-3 commits ago.

AnimeList has: "text: 1-0;2-3;3-4;4-5;5-6"  1-0 means that AniDB episode 1 doesn't have a mapping available at TVDB (so it should be ignored), while 2-3 means that AniDB episode 2 is s00e03 on TVDB,

**Comment by KurtzPT** [comment] 2018-07-04 09:21
It's still not working, using new library and deleted all Hama cache.

Some interesting information, it does seem that Hama downloads the correct thumb but also downloads the wrong one and applies it.

![image](https://user-images.githubusercontent.com/14930057/42268611-dd0dc7ac-7f73-11e8-8e0c-bb014d388446.png)
1st thumb is the wrong one, 2nd thumb is the right one. This just applies to this episode, all others only have the correct thumb without downloading extra ones.

[Nekomonogatari (Kuro) Tsubasa Family [anidb-9453].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/2162588/Nekomonogatari.Kuro.Tsubasa.Family.anidb-9453.agent-update.log)
[Nekomonogatari (Kuro) Tsubasa Family [anidb-9453].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/2162589/Nekomonogatari.Kuro.Tsubasa.Family.anidb-9453.filelist.log)

**Comment by ZeroQI** [comment] 2018-07-04 16:51
@KurtzPT I did notice the plex poster remaining, even after i added functions to clear posters not listed and images not being cached by plex. It seems Plex recognise the files and keep the metadata... It seems you have to remove the files from library, clean bundles, then add it back...

Thank you very much for this update. the reverse mapping is tricky, even more since i added multiple anidb xmls to cross reference everything, but it is getting more accurate every time. Glad to see it finally works as expected

@rcdailey  a movie should have the same name as the folder. can you confirm it is all good for you as well ?

**Closed** 2018-07-14 06:44 UTC
Labels: bug
