### ISSUE TITLE
HAMA not populating metadata.

### ISSUE THREAD

**Issue by myhe01** [ZeroQI/Hama.bundle#418] opened 2020-08-18 19:24 UTC
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/5092349/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/5092350/com.plexapp.system.log)
[Plex Media Server Logs_2020-08-18_15-19-35.zip](https://github.com/ZeroQI/Hama.bundle/files/5092385/Plex.Media.Server.Logs_2020-08-18_15-19-35.zip)

The following logs did not exist for me: series_root_folder.filelist.log, series_root_folder.scanner.log, series_root_folder.agent-search.log, or series_root_folder.agent-update.log.

![image](https://user-images.githubusercontent.com/28101069/90555223-092b4a80-e165-11ea-826d-98603b073287.png)
![image](https://user-images.githubusercontent.com/28101069/90555266-19dbc080-e165-11ea-8964-a3e5c9e26c21.png)

My issue is that HAMA does not want to populate any sort of metadata (titles, studio, poster, etc.) for any of the anime in my library. ASS seems to recognize the directories of the series. Fixing the match manually does not solve the issue.

![image](https://user-images.githubusercontent.com/28101069/90556154-6a075280-e166-11ea-86f8-b434d0fd0e80.png)
![image](https://user-images.githubusercontent.com/28101069/90556244-9327e300-e166-11ea-959e-3fd48f562f9e.png)
![image](https://user-images.githubusercontent.com/28101069/90556279-a3d85900-e166-11ea-8619-30fbb3935f6f.png)

HAMA and ASS do show up in the Scanner and Agent dropdowns.

![image](https://user-images.githubusercontent.com/28101069/90556335-c36f8180-e166-11ea-8ab0-2a00feab68cc.png)

I have installed and reinstalled HAMA a few times, always using the latest version. Have deleted the library, stopped Plex, updated HAMA (haven't touched ASS because it seems to work just fine), started plex, and recreated the library. Done the aforementioned several times.

The first time I installed HAMA, I had to go in and create the DataItems directories and their subdirectories.

![image](https://user-images.githubusercontent.com/28101069/90555382-44c61480-e165-11ea-8f03-256548102251.png)

I'm pretty sure I've been installing it into the proper directory.

![image](https://user-images.githubusercontent.com/28101069/90555710-cae25b00-e165-11ea-9f22-c2a7022dc93c.png)

I have ran
`chmod -R 777 '/mnt/ValleyForge/iocage/jails/plex/root/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/'`
from the shell a few times, trying to troubleshoot.
Also ran
`chown -R brendan:admin '/mnt/ValleyForge/iocage/jails/plex/root/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/'`

I'm pretty sure I've done everything right, and all of the fixes I've tried don't seem to work. Reddit and Google have no more answers for me. Kinda losing my mind over this.

**Comment by ZeroQI** [comment] 2020-08-18 20:47
Scanner logs were moved to Plex logs folder.
Since ASS is not updated then HAMA cannot determine the root folder from the scanner logs...

**Comment by myhe01** [comment] 2020-08-19 03:39
Deleted my library, stopped Plex. Reinstalled latest versions of ASS and HAMA, updated Plex. Recreated my library, issue still persists. Tried manually fixing the match, no dice.

Please find logs below.

[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/5093881/_root_.agent.log)
[_root_.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5093882/_root_.scanner.log)
[_root_--Plex Media Server-BRENDAN-NAS-Anime.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5093883/_root_--Plex.Media.Server-BRENDAN-NAS-Anime.filelist.log)
[_root_--Plex Media Server-BRENDAN-NAS-Anime.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5093884/_root_--Plex.Media.Server-BRENDAN-NAS-Anime.scanner.log)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/5093885/com.plexapp.agents.hama.log)
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/5093886/com.plexapp.system.log)
[Plex Media Scanner Analysis.log](https://github.com/ZeroQI/Hama.bundle/files/5093887/Plex.Media.Scanner.Analysis.log)
[Plex Media Scanner Deep Analysis.log](https://github.com/ZeroQI/Hama.bundle/files/5093888/Plex.Media.Scanner.Deep.Analysis.log)
[Plex Media Scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5093889/Plex.Media.Scanner.log)
[Plex Media Server Logs_2020-08-18_23-38-36.zip](https://github.com/ZeroQI/Hama.bundle/files/5093890/Plex.Media.Server.Logs_2020-08-18_23-38-36.zip)
[Plex Media Server.log](https://github.com/ZeroQI/Hama.bundle/files/5093891/Plex.Media.Server.log)

**Comment by ZeroQI** [comment] 2020-08-19 06:58
If the versions are the latest, why does it not recognise 'AniList' source in HAMA logs when loading settings?

Where in GitHub do you download HAMA?

**Comment by EndOfLine369** [comment] 2020-08-19 08:25
> If the versions are the latest, why does it not recognise 'AniList' source in HAMA logs when loading settings?

As the code was not updated to know this source in validations. Now fixed.

**Comment by ZeroQI** [comment] 2020-08-19 10:10
I cannot see any crash
- Agent and scanner are well installed as they are both showin in plex
- series show up in Plex so scanner is OK
- manual scan show series "Angel Beats!" in screenshot so we should have series logs since no errors are found in system or hama generic logs.
- Please attach "Angel Beats!.search.log" and "Angel Beats!.update.log" as all logs provided are useless. Hama logs are redirected to custom series logs to help troubleshooting Series

**Comment by myhe01** [comment] 2020-08-19 13:52
![image](https://user-images.githubusercontent.com/28101069/90643086-2c0b3c80-e201-11ea-9156-bac67cc0cb21.png)

From the readme, went to the green "Code" button, clicked "Download ZIP." Extracted folders, renamed it to Hama.bundle.

Logs for the individual series seem to report that metadata was pulled? Not sure, not too experienced in this sort of thing. Please find the requested logs, for a few different series, below.

[Angel Beats!.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/5096867/Angel.Beats.agent-search.log)
[Angel Beats!.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5096868/Angel.Beats.agent-update.log)
[Angel Beats!.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5096869/Angel.Beats.filelist.log)
[Angel Beats!.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5096870/Angel.Beats.scanner.log)
[Black Lagoon.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/5096871/Black.Lagoon.agent-search.log)
[Black Lagoon.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5096872/Black.Lagoon.agent-update.log)
[Black Lagoon.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5096873/Black.Lagoon.filelist.log)
[Black Lagoon.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5096874/Black.Lagoon.scanner.log)
[Blend S [anidb-12694].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/5096875/Blend.S.anidb-12694.agent-search.log)
[Demon Slayer [anidb-14107].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/5096876/Demon.Slayer.anidb-14107.agent-search.log)
[Demon Slayer [anidb-14107].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5096877/Demon.Slayer.anidb-14107.agent-update.log)
[Demon Slayer [anidb-14107].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5096878/Demon.Slayer.anidb-14107.filelist.log)
[Demon Slayer [anidb-14107].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5096879/Demon.Slayer.anidb-14107.scanner.log)
[Erased [anidb-11292].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/5096880/Erased.anidb-11292.agent-search.log)
[Erased [anidb-11292].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5096881/Erased.anidb-11292.agent-update.log)
[Erased [anidb-11292].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5096882/Erased.anidb-11292.filelist.log)
[Erased [anidb-11292].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5096883/Erased.anidb-11292.scanner.log)
[Lucky Star.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/5096884/Lucky.Star.agent-search.log)
[Lucky Star.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5096885/Lucky.Star.agent-update.log)
[Lucky Star.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5096886/Lucky.Star.filelist.log)
[Lucky Star.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5096887/Lucky.Star.scanner.log)
[Your Lie in April [anidb-10539].agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/5096888/Your.Lie.in.April.anidb-10539.agent-search.log)
[Your Lie in April [anidb-10539].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5096889/Your.Lie.in.April.anidb-10539.agent-update.log)
[Your Lie in April [anidb-10539].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5096890/Your.Lie.in.April.anidb-10539.filelist.log)
[Your Lie in April [anidb-10539].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5096891/Your.Lie.in.April.anidb-10539.scanner.log)

**Comment by ZeroQI** [comment] 2020-08-19 15:46
Now we are talking
- the Search is called and logged properly per series
- No error in com.plexapp.agents.hama.log nor in com.plexapp.system.log
- Update ends prematurely after:
```
=== AnimeLists.GetMetadata() ================================================================================================================================
tvdb_numbering: False
```
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AnimeLists.py
Line 85 is the last line displayed
it calls GetAniDBTVDBMapCustom and should display something and doesn't line 54, 55 or 58
- path or os.sep cause issues?

**Comment by EndOfLine369** [comment] 2020-08-19 19:56
@ZeroQI, agreed. It should say yes/no/failed for the `anime-list-custom.xml` check/load.
Any crash info _should_ be shown in the `_Logs/Anime/_root_.agent.log` file.

@myhe01, Please attach the file with its current info.

**Comment by myhe01** [comment] 2020-08-20 03:37
Uninstalling and reinstalling the Plex plugin didn't help, rip. Still having the exact same issue and symptoms.

Here's the file.
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/5100544/_root_.agent.log)

**Comment by EndOfLine369** [comment] 2020-08-20 04:05
@ZeroQI, there is no problem in `GetLibraryRootPath`. This is already called in `Log.Open()` which works fine.
EX: 
https://github.com/ZeroQI/Hama.bundle/blob/ea5e470844b7196431edda8e637cee00445cd3b7/Contents/Code/common.py#L104-L106
```
=============================================================================================================================================================
common.PlexLog(file="/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/Anime/Your Lie in April [anidb-10539].agent-update.log", movie=False)
[!] file:       "//Plex Media Server/BRENDAN-NAS/Anime/Your Lie in April [anidb-10539]/[Reaktor] Your Lie in April - E20 [1080p][x265][10-bit][Dual-Audio].mkv"
[ ] library:    "Anime"
[ ] root:       "//Plex Media Server/BRENDAN-NAS/Anime"
[ ] path:       "Your Lie in April [anidb-10539]"
[ ] Plex root:  "/Plex Media Server"
[ ] Log folder: "Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/Anime"
[ ] Log file:   "Your Lie in April [anidb-10539].agent-update.log"
[ ] Logger:     "0x809f48f00"
[ ] mode:       "w"
```

I suspect we have an infinite loop here caused by something in myhe01's setup. The only way it would stop printing is either it crashed (which we are not seeing any evidence of) or its stuck in an infinite loop

@myhe01,
Add the line `Log.Info("Checking: {}".format(dir))` to `AnimeLists.py` above line 50 shown below. Then trigger a refresh of a series and take a look at the `agent-update.log` for that series.

https://github.com/ZeroQI/Hama.bundle/blob/ea5e470844b7196431edda8e637cee00445cd3b7/Contents/Code/AnimeLists.py#L45-L59

EX:
```python
def GetAniDBTVDBMapCustom(media, movie):  
  AniDBTVDBMapCustom = None
  lib, root, path = common.GetLibraryRootPath(common.GetMediaDir(media, movie))
  dir = os.path.join(root, path)
  while dir and os.path.splitdrive(dir)[1] != os.sep:
    Log.Info("Checking: {}".format(dir))      ##### HERE ######
    scudlee_filename_custom = os.path.join(dir, SCHUDLEE_CUSTOM)
    if os.path.exists( scudlee_filename_custom ):
```

**Comment by myhe01** [comment] 2020-08-20 04:28
@EndOfLine369 

![image](https://user-images.githubusercontent.com/28101069/90716284-97452500-e27a-11ea-9a83-98b9a44991b0.png)

Added code to above line 50. Restarted Plex plugin. Clicked the "Refresh Metadata" option in the context menu for Darling in the FranXX, Lucky Star, and Watamote.

All of their log files are in the double-digit megabytes, lmao.

For Darling in the FranXX:

`=============================================================================================================================================================
common.PlexLog(file="/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/Anime/Darling in the FranXX.agent-update.log", movie=False)
[!] file:       "//Plex Media Server/BRENDAN-NAS/Anime/Darling in the FranXX/E24 Never Let Me Go.mkv"
[ ] library:    "Anime"
[ ] root:       "//Plex Media Server/BRENDAN-NAS/Anime"
[ ] path:       "Darling in the FranXX"
[ ] Plex root:  "/Plex Media Server"
[ ] Log folder: "Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/Anime"
[ ] Log file:   "Darling in the FranXX.agent-update.log"
[ ] Logger:     "0x809e43500"
[ ] mode:       "w"
=== Update() ================================================================================================================================================
id: anidb-13259, title: None, lang: en, force: True, movie: False
start: 2020-08-20 00:20:31,799761
=== AnimeLists.GetMetadata() ================================================================================================================================
tvdb_numbering: False
Checking: //Plex Media Server/BRENDAN-NAS/Anime/Darling in the FranXX
Checking: //Plex Media Server/BRENDAN-NAS/Anime
Checking: //Plex Media Server/BRENDAN-NAS
Checking: //Plex Media Server
Checking: //
Checking: //
Checking: //
Checking: //
Checking: //
Checking: //
Checking: //
Checking: //
Checking: //
Checking: //`

it's just `Checking: // ` all the way down to, hmm let's see...

line 1053525.

`Checking: //
Checking: //
Checking: //
Checking: //
Checking: //
Checking:`

Same deal for Lucky Star and Watamote.

[Darling in the FranXX.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5100663/Darling.in.the.FranXX.agent-update.log)
[Lucky Star.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5100664/Lucky.Star.agent-update.log)
[Watamote [anidb-9582].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5100665/Watamote.anidb-9582.agent-update.log)

Just realized the formatting is kinda off in this comment. Just check the logs and you'll see.

**Comment by EndOfLine369** [comment] 2020-08-20 04:32
Well, that confirms that its an infinite loop happening. You can remove that log line so it doesn't create large logs being stuck in that loop till this is fixed.
I wonder why ASS does not get stuck in a loop as it should be checking for the same file.

**Comment by ZeroQI** [comment] 2020-08-20 06:50
while dir and os.path.splitdrive(dir)[1] not in (os.sep, '//', ''):

**Comment by EndOfLine369** [comment] 2020-08-20 17:28
@ZeroQI, what is the reasoning of us going down below `root`? I can see no reason for this to be done. Then its a simple test of `dir == root` and break out of the loop.

**Comment by ZeroQI** [comment] 2020-08-20 19:07
@EndOfLine369 Good point. Avoiding questions from user putting it at root level I guess...

while dir and os.path.splitdrive(dir)[1] != os.sep and dir != root:

**Comment by EndOfLine369** [comment] 2020-08-20 19:56
No, we still want to process root. I personally only put in root if I need to do anything and we don't want to break any existing setups by users. Be it in the root or a folder within it. I'll get the logic tested updated later.

**Comment by EndOfLine369** [comment] 2020-08-21 00:09
@ZeroQI, Just update the test to `while dir` & clear `dir` once we've just processed root `dir = os.path.dirname(dir) if len(dir) > len(root) else ''`. See any issues with this locic?

HAMA EX:
```python
  while dir:
    Log.Info("Checking: {}".format(dir))
    scudlee_filename_custom = os.path.join(dir, SCHUDLEE_CUSTOM)
    if os.path.exists( scudlee_filename_custom ):
      try:
        AniDBTVDBMapCustom = XML.ElementFromString(Core.storage.load(scudlee_filename_custom))
        Log.Info("Local custom mapping file loaded: {}".format(scudlee_filename_custom))
      except:  Log.Error("Failed to open: '%s', error: '%s'" % (scudlee_filename_custom, e))
      else:    break
    dir = os.path.dirname(dir) if len(dir) > len(root) else ''  # Clear variable if we've just finished processing down to (and including) root
  else:  Log.Info("Local custom mapping file not present: {}".format(SCHUDLEE_CUSTOM))
```

**Comment by ZeroQI** [comment] 2020-08-21 08:00
@EndOfLine369 I thought you meant file system root but was obviously library root.
Nothing technically wrong with your code but i like shorter code and less tests, especially if simpler...

while len(dir)>=len(root):
  dir = os.path.dirname(dir)

**Comment by ZeroQI** [comment] 2020-08-23 19:50
because if there is an ep number, it is recognised... the anidbid is NOT recognised at file level, only folder level

**Closed by ZeroQI** 2020-08-23 19:50 UTC
Labels: bug
