### ISSUE TITLE
Anime Incorrectly being Identified

### ISSUE THREAD

**Issue by Sn0wCrack** [ZeroQI/Hama.bundle#163] opened 2018-01-19 00:11 UTC
It seems the series The Ancient Magus' Bride is being mismatched as it's mini-series spin-off MahoYome rather than the main series itself

![](https://i.imgur.com/35K9W1G.png)

There seems to be a bit about it in my logs here:
https://pastebin.com/raw/CPGfsvMG

**Comment by ZeroQI** [comment] 2018-01-19 09:34
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=12942 The Ancient Magus` Bride
http://anidb.net/perl-bin/animedb.pl?show=anime&aid=11982 The Ancient Magus` Bride: Those Awaiting a Star

Anidb title database: https://raw.githubusercontent.com/ScudLee/anime-lists/master/animetitles.xml
```
	<anime aid="12942">
		<title type="main" xml:lang="x-jat">Mahou Tsukai no Yome</title>
		<title type="official" xml:lang="de">Die Braut des Magiers</title>
		<title type="official" xml:lang="en">The Ancient Magus` Bride</title>
		<title type="official" xml:lang="fr">The Ancient Magus` Bride</title>
		<title type="official" xml:lang="ja">魔法使いの嫁</title>
		<title type="official" xml:lang="zh-Hans">魔法使的新娘</title>
		<title type="official" xml:lang="zh-Hant">魔法使的新娘</title>
		<title type="short" xml:lang="x-jat">Mahoyome</title>
		<title type="syn" xml:lang="bg">Жената на магьосника</title>
	</anime>
	<anime aid="11982">
		<title type="main" xml:lang="x-jat">Mahou Tsukai no Yome: Hoshi Matsu Hito</title>
		<title type="official" xml:lang="en">The Ancient Magus` Bride: Those Awaiting a Star</title>
		<title type="official" xml:lang="fr">The Ancient Magus Bride</title>
		<title type="official" xml:lang="ja">魔法使いの嫁 星待つひと</title>
		<title type="official" xml:lang="pl">Oblubienica czarnoksiężnika</title>
		<title type="official" xml:lang="tr">Kadim Büyücünün Gelini: Bir Yıldızı Bekleyenler</title>
		<title type="official" xml:lang="zh-Hans">魔法使的新娘 等待繁星之人</title>
		<title type="short" xml:lang="x-jat">Mahoyome OVA</title>
		<title type="syn" xml:lang="en">Mahou Tsukai no Yome OVA</title>
		<title type="syn" xml:lang="fr">The Ancient Magus Bride - En attendant une étoile</title>
		<title type="syn" xml:lang="ru">Невеста чародея</title>
		<title type="syn" xml:lang="x-jat">Mahoutsukai no Yome: Hoshi Matsu Hito</title>
	</anime>
```

```
2018-01-19 11:01:03,240 (24f4) :  INFO (logkit:16) - AniDB.Search() - orig_title: 'The Ancient Magus Bride', orig_title_cleansed: 'the ancient magus bride'
2018-01-19 11:01:03,460 (24f4) :  INFO (logkit:16) - [+] score: 100, aid: 11982, title: 'The Ancient Magus Bride', title_cleansed: The Ancient Magus Bride
2018-01-19 11:01:03,460 (24f4) :  INFO (logkit:16) - [=] best_score: 100, best_aid: 11982, best_title: The Ancient Magus Bride
2018-01-19 11:01:03,460 (24f4) :  INFO (logkit:16) - elapsed_time: 0.219
```

You want "The Ancient Magus Bride" to be assigned to anidbid 12942 but it gets assigned to 11982
serie: The Ancient Magus` Bride
spinof: The Ancient Magus Bride

well if you had put the apostrophe it should have matched exactly so not going to cleaned string match but as it is now it is a direct match for the spinoff due to its french title.

Working as designed as you didn't labelled it on any Exact AniDB title.
Either get both series title amended in AniDB XML (they won't probably) or **label it "The Ancient Magus` Bride" with the normal single apostrophe or backward AniDB one.**

**Closed** 2018-01-19 10:10 UTC
