### ISSUE TITLE
Missing episodes from multiple series

### ISSUE THREAD

**Issue by teirce** [ZeroQI/Hama.bundle#233] opened 2018-07-13 03:05 UTC
I have multiple series that are partially matching with hama scanner. There does not seem to be a pattern, and refreshing metadata / re-scanning library does not help. Here are some limited examples:

Missing episode 19, 20, 23:
![sg](https://user-images.githubusercontent.com/6893805/42670164-17004642-860e-11e8-8e57-3da0dd337b46.png)

Missing episode 9, 11:
![so](https://user-images.githubusercontent.com/6893805/42670061-a52fb796-860d-11e8-8d4c-c2e38f3a22d2.png)

Scratching my head since the metadata and other episodes are retrieving correctly. Here are folder breakdowns of S;G as an example:
```
\---Steins Gate
    |   
    +---Season 00
    |       S00E01 - Egoistic Poriomania.mkv
    |       S00E23 - Divide By Zero.mkv
    |       
    \---Season 01
            S01E01 - Prologue of the Beginning and Ending.mkv
            S01E02 - Paranoia of Time Leaps.mkv
            S01E03 - Paranoia of Parallel Process.mkv
            S01E04 - Rendezvous of Abstract Fluctuation.mkv
            S01E05 - Rendezvous of Electrical Charge Conflict.mkv
            S01E06 - Butterfly Effect`s Divergence.mkv
            S01E07 - Divergence Singularity.mkv
            S01E08 - Homeostasis of Dreams.mkv
            S01E09 - Homeostasis of Illusions.mkv
            S01E10 - Homeostasis of Complements.mkv
            S01E11 - Dogma of Space-Time Boundary.mkv
            S01E12 - Dogma in Ergosphere.mkv
            S01E13 - Necrosis of Metaphysical.mkv
            S01E14 - Necrosis of Physical.mkv
            S01E15 - Missing Link Necrosis.mkv
            S01E16 - Sacrificial Necrosis.mkv
            S01E17 - Made in Complex.mkv
            S01E18 - Androgynous Fractale.mkv
            S01E19 - Infinite Chain of Apoptosis.mkv
            S01E20 - Finalize Apoptosis.mkv
            S01E21 - Paradox Meltdown.mkv
            S01E22 - Being Meltdown.mkv
            S01E23 - Open the Steins Gate.mkv
            S01E24 - Achievement Point.mkv
```
Fairly sure I followed configuration correctly.

If there are any specific logs I can look at to troubleshoot or provide for debugging, please let me know.

**Comment by ZeroQI** [comment] 2018-07-13 07:01
Hama is the metadata agent.

As per the read-me, If all video files are showing in plex at the right season and episode number, the scanner did its job.

Clearly here the scanner didn't since it is missing episodes so it is a scanner issue.

Absolute Series Scanner is the scanner I wrote BUT you give no indication of using it.

If you are indeed using it, please create a bug report under the scanner and attach Absolute Series Scanner logs, all is in its readme and the link to ASS scanner is at the top of Hama readme.

Closing this bug report as it is a scanner issue and nothing to do with the agent.

**Closed by ZeroQI** 2018-07-13 07:01 UTC

**Comment by ZeroQI** [comment] 2018-07-14 01:14
I did reproduce and logging was used season folder as name. corrected.
Have no issue with filenames so probably using default series scanner. if not raise ticket on scanner page.

```
Library: 'no valid X-Plex-Token.id', root: 'C:\Users\benja\Videos\_temp2', path: 'Steins Gate\Season 01', files: '3', dirs: '0', Plex scan date: 2018-07-14 02:11:43
=============================================================================================================================================================
No forced guid found in folder name nor id file
misc_count: {'open': 1, 'finalize': 1, 'chain': 1, 'of': 1, 'apoptosis': 2, 'infinite': 1, 'the': 1, 's01e19': 1, 's01e23': 1, 's01e20': 1}
"Steins Gate" s01e019                         "__" "Infinite Chain of Apoptosis" "S01E19 - Infinite Chain of Apoptosis.mkv"
"Steins Gate" s01e020                         "__" "Finalize Apoptosis" "S01E20 - Finalize Apoptosis.mkv"
"Steins Gate" s01e023                         "__" "Open The" "S01E23 - Open the Steins Gate.mkv"
root level manual call to Grouping folders
```

**Comment by teirce** [comment] 2018-07-14 02:08
My apologies for opening an issue in the wrong project. I assumed that ASS came packaged with HAMA, I did not realize they would come separately. It makes sense, I just did not understand the readme properly.

After installing ASS and creating a new library, it was replicating the issue much the same as default plex series scanner. 

The culprit for this issue is not related to HAMA or ASS. The only conclusion I have come to is that somehow `.plexignore` files I had were causing episodes to go missing. After reworking `.plexignore` files I had, episodes were picked up properly by ASS.

**Comment by ZeroQI** [comment] 2018-07-14 02:19
@teirce No problem, i just get annoyed since i tried to have read-me written to avoid these...
ASS is separate as you can use it with youtube agent too or for tv series as well as a replacement over Plex series scanner (supports logging per series, grouping folders, etc)
Thanks for taking the time to reply. Yeah, my scanner do support .plexignore files, ASS logs per series in hama agent data folders will indicate  it is skipping files.
Had to include it since plex didn't manage them too well...

Glad to ear it is working
