### ISSUE TITLE
[BETA] Weird episode images.

### ISSUE THREAD

**Issue by KurtzPT** [ZeroQI/Hama.bundle#197] opened 2018-05-12 17:45 UTC
The anime folder: Genki Bakuhatsu Ganbaruger [anidb-5816]

While hama is getting the metadata the following episode pictures appear all over:

![image](https://user-images.githubusercontent.com/14930057/39960096-437c68b0-5614-11e8-9985-ea01c668cca4.png)

**NOTES:**

This anime doesn't have a tvdbid on the anime-list-master file (it might be the reason for the weird pictures):

> === Update ==================================================================================================================================================
id: anidb-5816, title: None, lang: en, force: True, movie: False
> AnimeLists.GetMetadata() - AniDBid: 5816, TVDBid: unknown, defaulttvdbseason: 1, episodeoffset: 0, name: Genki Bakuhatsu Ganbaruger

I already asked Sculee to add the correct tvdbid meanwhile, but it shouldn't generate these images if there's no tvdbid.

**Comment by ZeroQI** [comment] 2018-05-13 07:42
@KurtzPT Thumbs should be TheTVDB only. I hightly doubt that TheTVDB code gave the screenshot wrongly, as it would need to download the series JSON, get the video ID from that, get the advanced video details to get the screenshot URL... On top of that, i include now only the metadata for present episodes to avoid useless data
What does happen when you go to the thumbs url indicated on the agent logs update chart at the end, for the episode 'thumbs' field ? i recon it is empty and Plex would have used part of the series poster and it trigger a bug possibly... Will reproduce once home but expect it impacts only you, If not will correct...

**Comment by KurtzPT** [comment] 2018-05-13 12:06
Having the multi-thread makes the logs all messed up, just look at this order (Shows title for episode 46, then for ep 45, than the directors for episode 44...):

> [1] title                          Sources: (AniDB),TheTVDB                                               Type: str                   Value: 'We are a life-force explosion!' new season: 1 , new_episode: 46 
[1] title                          Sources: (AniDB),TheTVDB                                               Type: str                   Value: 'Three devil kings, reborn!' new season: 1 , new_episode: 45 
[!] absolute_index                 Sources: TheTVDB                                                       Type: NoneType              Inside : []
[1] directors                      Sources: (AniDB),TheTVDB                                               Type: list                  Value: 'Kawase Toshifumi' new season: 1 , new_episode: 44 
[!] summary                        Sources: AniDB,TheTVDB                                                 Type: NoneType              Inside : []
[!] language source: AniDB, rank: 4, found: False, language_rank: ''
[!] producers                      Sources: AniDB,TheTVDB                                                 Type: SetObject             Inside : []
[!] summary                        Sources: AniDB,TheTVDB                                                 Type: NoneType              Inside : []
[!] guest_stars                    Sources: None                                                          Type: SetObject             Inside : []
[1] title                          Sources: (AniDB),TheTVDB                                               Type: str                   Value: 'Final last great decisive battle!' new season: 1 , new_episode: 47 
[1] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Type: dict                  Value: '{'https://thetvdb.plexapp.com/banners/episodes/269873/4625910.jpg': ('TheTVDB/episodes/4625910.jpg', 1, None)}' new season: 1 , new_episode: 12 
thumbs: https://thetvdb.plexapp.com/banners/episodes/269873/4625910.jpg

Anyway, if there's no TVDBid on anime-list-masters.xml, it shouldn't give any URL at all unless for the thumbs field, correct me if I'm mistaken. As you can see, for the episode 12, it returned the above URL, even though that image isn't from the anime nor it was the picture displayed after it was done getting all the metadata. 

Since I was scanning a lot of animes at  that time, my only guess is that having an anime without a know TVDBid from the xml file, will mess up either the multi-thread logic and makes that logic get some random image, or it's just the logic of handling thumbs without a TVDBid.

**NOTE:**

I have fixed this myself by adding the missing TVDBid from anime-list-master.xml as you can see on a later update I did:

> === Update ==================================================================================================================================================
id: anidb-5816, title: Genki Bakuhatsu Ganbaruger, lang: en, force: True, movie: False
AnimeLists.GetMetadata() - AniDBid: 5816, TVDBid: 333830, defaulttvdbseason: 1, episodeoffset: 0, name: Genki Bakuhatsu Ganbaruger
anidbTvdbMapping() - mappingList: {'defaulttvdbseason': '1', 'name': 'Genki Bakuhatsu Ganbaruger', 'episodeoffset': '0'}

![image](https://user-images.githubusercontent.com/14930057/39967147-613195ac-56ae-11e8-82b6-7413dd2ebe99.png)

**Comment by ZeroQI** [comment] 2018-05-14 03:16
cannot reproduce and working now, closing. reopen if you ever get the issue on another series and include full agent logs

**Closed by ZeroQI** 2018-05-14 03:16 UTC
