### ISSUE TITLE
TheTVDB - Authorization Error: <urlopen error [Errno 11001] getaddrinfo failed>

### ISSUE THREAD

**Issue by smoon1895** [ZeroQI/Hama.bundle#376] opened 2019-12-23 17:35 UTC
Hi,

since yesterday i am receiving the following error from thetvdb using the hama bundle:
Authorization Error: <urlopen error [Errno 11001] getaddrinfo failed>

I already did the following:
- I complete installed hama.bundle from the scratch again with the newest release

Rebooting my server does not solve the problem.

Here´s the necessary part from the lofgile:

```
2019-12-23 18:28:51,084 (13e0) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.hama/messagi
ng/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzN
Qpmb3JjZWIwczgKcGVyaW9kaWNzNgoxMzU4MzhzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAK
bWVkaWFfdHlwZXM0NQpjb20ucGxleGFwcC5hZ2VudHMuaGFtYTovL2FuaWRiLTEzOTQ1P2xhbmc9ZW5zNApndWlkczExCmFuaWRiLTEzOTQ1czIKaWRyMAo
_
2019-12-23 18:28:51,117 (13e0) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.hama/messagi
ng/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzN
Qpmb3JjZWIwczgKcGVyaW9kaWNzNgoxMzU4MzhzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAK
bWVkaWFfdHlwZXM0NQpjb20ucGxleGFwcC5hZ2VudHMuaGFtYTovL2FuaWRiLTEzOTQ1P2xhbmc9ZW5zNApndWlkczExCmFuaWRiLTEzOTQ1czIKaWRyMAo
_
2019-12-23 18:28:51,118 (13e0) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.hama://anidb-13945?lang
=en
2019-12-23 18:28:51,121 (13e0) :  DEBUG (model:234) - Deserializing from C:\Users\smoon\AppData\Local\Plex Media Server
\Metadata\TV Shows\0\eb4da95d75e59fdd0de6f0efa27553c41293e57.bundle\Contents\com.plexapp.agents.hama\Info.xml
2019-12-23 18:28:51,246 (13e0) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/135838/t
ree'
2019-12-23 18:28:51,296 (13e0) :  DEBUG (sandbox:19) - [!] folder: 'C:\Users\smoon\AppData\Local\Plex Media Server\Plug
-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime EN'created
2019-12-23 18:28:51,298 (13e0) :  INFO (common:151) - ==== common.PlexLog(file="C:\Users\smoon\AppData\Local\Plex Media
 Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime EN\Vinland Saga.agent-update.log")
2019-12-23 18:28:51,496 (13e0) :  DEBUG (networking:143) - Requesting 'https://api.thetvdb.com/login'
2019-12-23 18:28:51,515 (13e0) :  DEBUG (sandbox:19) - TheTVDB - Authorization Error: <urlopen error [Errno 11001] geta
ddrinfo failed>
2019-12-23 18:28:51,546 (13e0) :  DEBUG (networking:138) - Fetching 'https://api.thetvdb.com/series/359274?en' from the
 HTTP cache
2019-12-23 18:28:51,612 (13e0) :  DEBUG (sandbox:19) - Downloaded URL 'https://api.thetvdb.com/series/359274?en'
2019-12-23 18:28:51,627 (13e0) :  DEBUG (networking:143) - Requesting 'https://api.thetvdb.com/login'
2019-12-23 18:28:51,661 (13e0) :  DEBUG (sandbox:19) - TheTVDB - Authorization Error: <urlopen error [Errno 11001] geta
ddrinfo failed>
2019-12-23 18:28:51,700 (13e0) :  DEBUG (networking:143) - Requesting 'https://api.thetvdb.com/series/359274/actors'
2019-12-23 18:28:51,757 (13e0) :  DEBUG (networking:143) - Requesting 'https://api.thetvdb.com/login'
2019-12-23 18:28:51,799 (13e0) :  DEBUG (sandbox:19) - TheTVDB - Authorization Error: <urlopen error [Errno 11001] geta
ddrinfo failed>
2019-12-23 18:28:51,838 (13e0) :  DEBUG (networking:143) - Requesting 'https://api.thetvdb.com/series/359274/episodes?p
age=1'
2019-12-23 18:28:51,891 (13e0) :  DEBUG (networking:143) - Requesting 'https://api.thetvdb.com/login'
2019-12-23 18:28:51,928 (13e0) :  DEBUG (sandbox:19) - TheTVDB - Authorization Error: <urlopen error [Errno 11001] geta
ddrinfo failed>
2019-12-23 18:28:51,959 (13e0) :  DEBUG (networking:143) - Requesting 'https://api.thetvdb.com/series/359274/images'
2019-12-23 18:28:52,040 (13e0) :  DEBUG (networking:143) - Requesting 'http://api.anidb.net:9001/httpapi?request=anime&
client=hama&clientver=1&protover=1&aid=13945'
2019-12-23 18:28:52,147 (13e0) :  DEBUG (sandbox:19) - Downloaded URL 'http://api.anidb.net:9001/httpapi?request=anime&
client=hama&clientver=1&protover=1&aid=13945'
2019-12-23 18:28:58,440 (13e0) :  DEBUG (networking:143) - Requesting 'http://api.tmdb.org/3/movie/88803?api_key=7f4a0b
d0bd3315bb832e17feda70b5cd&append_to_response=releases,credits,trailers,external_ids&language=en'
2019-12-23 18:28:58,549 (13e0) :  DEBUG (sandbox:19) - Downloaded URL 'http://api.tmdb.org/3/movie/88803?api_key=7f4a0b
d0bd3315bb832e17feda70b5cd&append_to_response=releases,credits,trailers,external_ids&language=en'
2019-12-23 18:28:58,621 (13e0) :  DEBUG (networking:143) - Requesting 'http://api.tmdb.org/3/configuration?api_key=7f4a
0bd0bd3315bb832e17feda70b5cd'
2019-12-23 18:28:58,826 (13e0) :  DEBUG (sandbox:19) - Downloaded URL 'http://api.tmdb.org/3/configuration?api_key=7f4a
0bd0bd3315bb832e17feda70b5cd'
2019-12-23 18:28:58,924 (13e0) :  DEBUG (networking:138) - Fetching 'http://webservice.fanart.tv/v3/tv/359274?api_key=c
fa9dc054d221b8d107f8411cd20b13f' from the HTTP cache
2019-12-23 18:28:58,986 (13e0) :  DEBUG (sandbox:19) - Downloaded URL 'http://webservice.fanart.tv/v3/tv/359274?api_key
=cfa9dc054d221b8d107f8411cd20b13f'
2019-12-23 18:29:00,440 (13e0) :  DEBUG (model:229) - Serializing to C:\Users\smoon\AppData\Local\Plex Media Server\Met
adata\TV Shows\0\eb4da95d75e59fdd0de6f0efa27553c41293e57.bundle\Contents\com.plexapp.agents.hama\Info.xml
2019-12-23 18:29:00,446 (13e0) :  DEBUG (runtime:88) - Sending packed state data (604 bytes)
2019-12-23 18:29:00,446 (13e0) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

Just let me know if you need more information:

btw.: heres the information from the "Vinland Saga.agent-update" Log:

https://www.senshi.jp/Vinland-Saga.agent-update.log

Maybe it´s useful, but:

OS: Windows Server 2012 R2, Plex 1.18.3.2156

thanks

Chris

**Comment by smoon1895** [comment] 2019-12-24 15:07
Hi,

it seems to be a problem in general with thetvdb. The Plex internal TheTVDB Plugin also has the same problem. Maybe they changed something at theit API?

Best regards

Chris

**Comment by ZeroQI** [comment] 2020-01-08 10:20
Is the issue still present?

**Comment by smoon1895** [comment] 2020-01-09 07:43
Yes it is, but i found a solution which at least temporarily solved the problem for me. I added the ip-adresses of the tvdb hosts to my local hosts configuration file, since then it works again.

when i remove/disable this entries the problem comes back. I dunno what it is, but the dns resolving is working fine even without the hosts entries. Everything on the server works fine, also all others apis instead of tvdb.

**Comment by ZeroQI** [comment] 2020-01-09 10:57
Look like a Plex dns resolution bug that impact mainly TheTVDB for some reason...

**Comment by sven-7** [comment] 2020-01-11 20:57
I can confirm modifying the localhost file fix works for me as well.

**Comment by smoon1895** [comment] 2020-01-12 11:20
Well, i checked a littlebit around. It seems to be totally a dns resolution bug within Plex. I´m not 100 percent sure, but i will investigate more on this.

Meanwhile: To temporarily solve this issue you can set the dns information for the affected tvdb hosts in your local hosts file. The problem will then no longer occur.

If i find out more i will open a Bug-report on Plex.

**Comment by sven-7** [comment] 2020-01-20 04:10
@smoon1895 -- Did they close this ticket on Plex? If not, can you post it?

**Comment by ZeroQI** [comment] 2020-02-12 22:31
https://forums.thetvdb.com/viewtopic.php?f=3&t=61687
https://forums.plex.tv/t/tvdb-removing-legacy-ssl-support-tv-metadata-failures-now-from-plex/524442/47

Look like thetvdb url https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/TheTVDBv2.py line 18 and 19 have to revert to http instead of https...

Anybody can test and report please ?

**Comment by ZeroQI** [comment] 2020-03-06 12:24
Anybody can test and report please ?

**Comment by sven-7** [comment] 2020-03-06 13:34
Nothing seems to be broken by changing it. It does seem slower? Not sure if that's something else at play.

**Comment by ZeroQI** [comment] 2020-03-06 14:14
So it works with the fix in place?
If so will put on the master code and close this bug report then as we have too many open...

**Comment by sven-7** [comment] 2020-03-06 14:21
Wait. It's failing. I had to look in the main HAMA log and make sure my caches were cleared properly. 

Here is a snippet:

```
2020-03-06 09:16:04,528 (2bf0) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/276939/tree'
2020-03-06 09:16:04,573 (2bf0) :  INFO (common:135) - ==== common.PlexLog(file="C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series\Haikyu!!.agent-update.log")
2020-03-06 09:16:04,651 (2bf0) :  DEBUG (networking:143) - Requesting 'http://api.thetvdb.com/login'
2020-03-06 09:16:04,664 (2bf0) :  ERROR (networking:196) - Error opening URL 'http://api.thetvdb.com/login'
2020-03-06 09:16:04,664 (2bf0) :  DEBUG (sandbox:19) - TheTVDBv2.LoadFileTVDB() - Authorization Error: HTTP Error 307: Temporary Redirect
2020-03-06 09:16:04,671 (2bf0) :  DEBUG (networking:143) - Requesting 'http://api.thetvdb.com/series/278157?en'
2020-03-06 09:16:04,733 (2bf0) :  ERROR (networking:196) - Error opening URL 'http://api.thetvdb.com/series/278157?en'
2020-03-06 09:16:04,733 (2bf0) :  DEBUG (sandbox:19) - ERROR: common.LoadFile() - issue loading url: 'http://api.thetvdb.com/series/278157?en', filename: 'series_en.json', Headers: {'Content-type': 'application/json', 'Accept-Language': 'en', 'User-agent': 'Plex/HAMA'}, Exception: 'HTTP Error 401: '
2020-03-06 09:16:07,209 (2bf0) :  DEBUG (model:229) - Serializing to C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Metadata\TV Shows\7\c4d8f651eda5eaac20d0639653c23c02c1c308c.bundle\Contents\com.plexapp.agents.hama\Info.xml
2020-03-06 09:16:07,213 (2bf0) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2020-03-06 09:16:07,213 (2bf0) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
2020-03-06 09:18:11,154 (1bfc) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTExCnMxNgo4ZDI1YWY0YTY0ZTQ4MzM4czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczEKOHM3CmVwaXNvZGVzMTAKQ2hhbGxlbmdlcnM0Cm5hbWVzMQoxczgKZXBpc29kaWNzMjMKSGFpa3l1ISEgW3R2ZGIyLTI3ODE1N11zNApzaG93czEKNHM2CnNlYXNvbm5zNAp5ZWFyczgwCkYlM0ElNUNTZXJpZXMlMjBHTCU1Q0hhaWt5dSUyMSUyMSU1Q0hhaWt5dSUyMSUyMSUyMC0lMjA2OCUyMC0lMjBDaGFsbGVuZ2VyJTJFbWt2czgKZmlsZW5hbWVzNDAKNTc5MzY4Y2VhOTc5ODFiOTFhYjVkNDM4ZGY3MGZjMTJmMTY3NzgyYXM4CnBsZXhIYXNoczcKMTQzNjk2NnM4CmR1cmF0aW9uczYKMjc2OTM5czIKaWRyMAo_
2020-03-06 09:18:11,157 (1bfc) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-03-06 09:18:11,158 (1bfc) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTExCnMxNgo4ZDI1YWY0YTY0ZTQ4MzM4czE3Cm9wZW5TdWJ0aXRsZXNIYXNoczEKOHM3CmVwaXNvZGVzMTAKQ2hhbGxlbmdlcnM0Cm5hbWVzMQoxczgKZXBpc29kaWNzMjMKSGFpa3l1ISEgW3R2ZGIyLTI3ODE1N11zNApzaG93czEKNHM2CnNlYXNvbm5zNAp5ZWFyczgwCkYlM0ElNUNTZXJpZXMlMjBHTCU1Q0hhaWt5dSUyMSUyMSU1Q0hhaWt5dSUyMSUyMSUyMC0lMjA2OCUyMC0lMjBDaGFsbGVuZ2VyJTJFbWt2czgKZmlsZW5hbWVzNDAKNTc5MzY4Y2VhOTc5ODFiOTFhYjVkNDM4ZGY3MGZjMTJmMTY3NzgyYXM4CnBsZXhIYXNoczcKMTQzNjk2NnM4CmR1cmF0aW9uczYKMjc2OTM5czIKaWRyMAo_
2020-03-06 09:18:11,160 (1bfc) :  INFO (agentkit:957) - Searching for matches for {'openSubtitlesHash': '8d25af4a64e48338', 'episode': '8', 'name': 'Challenger', 'episodic': '1', 'show': 'Haikyu!! [tvdb2-278157]', 'season': '4', 'plexHash': '579368cea97981b91ab5d438df70fc12f167782a', 'filename': 'F%3A%5CSeries%20GL%5CHaikyu%21%21%5CHaikyu%21%21%20-%2068%20-%20Challenger%2Emkv', 'year': None, 'duration': '1436966', 'id': '276939'}
2020-03-06 09:18:11,164 (1bfc) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/276939/tree'
2020-03-06 09:18:11,220 (1bfc) :  INFO (common:135) - ==== common.PlexLog(file="C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series\Haikyu!!.agent-search.log")
2020-03-06 09:18:11,223 (1bfc) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2020-03-06 09:18:11,223 (1bfc) :  DEBUG (runtime:924) - Response: [200] str, 652 bytes
2020-03-06 09:18:17,200 (3208) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTMKczQKMjAxNHM0CnllYXJzNgoyNzY5MzlzMgppZHMxMQpjbGVhci1jYWNoZXM0CnNob3dyMAo_
2020-03-06 09:18:17,200 (3208) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-03-06 09:18:17,203 (3208) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlNlYXJjaA__/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoyCmRpY3QKZGljdAo2CnMyCmVuczQKbGFuZ2IxczYKbWFudWFsYjFzNwpwcmltYXJ5aTAKczcKdmVyc2lvbnIxCnM2Cmt3YXJnc3M3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZTMKczQKMjAxNHM0CnllYXJzNgoyNzY5MzlzMgppZHMxMQpjbGVhci1jYWNoZXM0CnNob3dyMAo_
2020-03-06 09:18:17,203 (3208) :  INFO (agentkit:957) - Searching for matches for {'show': 'clear-cache', 'id': '276939', 'year': '2014'}
2020-03-06 09:18:17,204 (3208) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/276939/tree'
2020-03-06 09:18:17,259 (3208) :  INFO (common:135) - ==== common.PlexLog(file="C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series\Haikyu!!.agent-search.log")
2020-03-06 09:18:17,266 (3208) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2020-03-06 09:18:17,266 (3208) :  DEBUG (runtime:924) - Response: [200] str, 656 bytes
2020-03-06 09:18:20,852 (2e54) :  DEBUG (runtime:717) - Handling request GET /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoyNzY5MzlzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZXM0Ngpjb20ucGxleGFwcC5hZ2VudHMuaGFtYTovL3R2ZGIyLTI3ODE1Nz9sYW5nPWVuczQKZ3VpZHMxMgp0dmRiMi0yNzgxNTdzMgppZHIwCg__
2020-03-06 09:18:20,854 (2e54) :  DEBUG (runtime:49) - Received packed state data (80 bytes)
2020-03-06 09:18:20,854 (2e54) :  DEBUG (runtime:814) - Found route matching /:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNgoyNzY5MzlzNApkYmlkaTAKczcKdmVyc2lvbm5zMTAKcGFyZW50R1VJRG5zOApwYXJlbnRJRHM3ClRWX1Nob3dzMTAKbWVkaWFfdHlwZXM0Ngpjb20ucGxleGFwcC5hZ2VudHMuaGFtYTovL3R2ZGIyLTI3ODE1Nz9sYW5nPWVuczQKZ3VpZHMxMgp0dmRiMi0yNzgxNTdzMgppZHIwCg__
2020-03-06 09:18:20,855 (2e54) :  DEBUG (model:32) - Loading model with GUID com.plexapp.agents.hama://tvdb2-278157?lang=en
2020-03-06 09:18:20,855 (2e54) :  DEBUG (model:234) - Deserializing from C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Metadata\TV Shows\7\c4d8f651eda5eaac20d0639653c23c02c1c308c.bundle\Contents\com.plexapp.agents.hama\Info.xml
2020-03-06 09:18:20,984 (2e54) :  DEBUG (networking:143) - Requesting 'http://127.0.0.1:32400/library/metadata/276939/tree'
2020-03-06 09:18:21,019 (2e54) :  INFO (common:135) - ==== common.PlexLog(file="C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems\_Logs\Anime Series\Haikyu!!.agent-update.log")
2020-03-06 09:18:21,096 (2e54) :  DEBUG (networking:143) - Requesting 'http://api.thetvdb.com/login'
2020-03-06 09:18:21,107 (2e54) :  ERROR (networking:196) - Error opening URL 'http://api.thetvdb.com/login'
2020-03-06 09:18:21,107 (2e54) :  DEBUG (sandbox:19) - TheTVDBv2.LoadFileTVDB() - Authorization Error: HTTP Error 307: Temporary Redirect
2020-03-06 09:18:21,115 (2e54) :  DEBUG (networking:143) - Requesting 'http://api.thetvdb.com/series/278157?en'
2020-03-06 09:18:21,194 (2e54) :  ERROR (networking:196) - Error opening URL 'http://api.thetvdb.com/series/278157?en'
2020-03-06 09:18:21,196 (2e54) :  DEBUG (sandbox:19) - ERROR: common.LoadFile() - issue loading url: 'http://api.thetvdb.com/series/278157?en', filename: 'series_en.json', Headers: {'Content-type': 'application/json', 'Accept-Language': 'en', 'User-agent': 'Plex/HAMA'}, Exception: 'HTTP Error 401: '
2020-03-06 09:18:23,382 (2e54) :  DEBUG (model:229) - Serializing to C:\Users\RAFTEL3\AppData\Local\Plex Media Server\Metadata\TV Shows\7\c4d8f651eda5eaac20d0639653c23c02c1c308c.bundle\Contents\com.plexapp.agents.hama\Info.xml
2020-03-06 09:18:23,387 (2e54) :  DEBUG (runtime:88) - Sending packed state data (104 bytes)
2020-03-06 09:18:23,388 (2e54) :  DEBUG (runtime:924) - Response: [200] str, 16 bytes
```

**Comment by ZeroQI** [comment] 2020-03-17 22:38
2020-03-06 09:16:04,651 (2bf0) :  DEBUG (networking:143) - Requesting 'http://api.thetvdb.com/login'
2020-03-06 09:16:04,664 (2bf0) :  ERROR (networking:196) - Error opening URL 'http://api.thetvdb.com/login'
2020-03-06 09:16:04,664 (2bf0) :  DEBUG (sandbox:19) - TheTVDBv2.LoadFileTVDB() - Authorization Error: HTTP Error 307: Temporary Redirect

https://airbrake.io/blog/http-errors/307-temporary-redirect

Either it is temporary, or the API changed...

https://forums.thetvdb.com/viewtopic.php?f=122&t=63148
2020-03-11 We are aware of the slowness and are taking measures to optimize.

**Comment by smoon1895** [comment] 2020-03-26 09:03
oookay, i was just testing around in the last days and i think i found a solution:

After trying out different things to get that working again i changed the caching dns adresses of my network configuration a few days ago to 8.8.8.8 and 8.8.4.4 (These are Google DNS)

Since then it is working fine again without any error messages in the log files.

**Comment by ZeroQI** [comment] 2020-03-26 09:06
Weird...

Should not be related to dns...
Must have been local or tvdb temp issue.
Closing for now

**Closed by ZeroQI** 2020-03-26 09:06 UTC
Labels: Third Party Issue
