### ISSUE TITLE
How to map Re:ZERO Director's Cut

### ISSUE THREAD

**Issue by jvmunhoz** [ZeroQI/Hama.bundle#446] opened 2021-01-30 13:47 UTC
I'm having difficulties trying to match the [Director's Cut of the S01 of  Re:Zero kara Hajimeru Isekai Seikatsu](https://anidb.net/anime/11370) with anything on the mapping due to it [not being a separate series](https://thetvdb.com/series/re-zero-starting-life-in-another-world/seasons/alternate/1) on tvdb.

I put them as Others 01 through 13, as classified on the anidb page, and the logs show that it pulls some right metadata (like airdate and summary) but the episode name and other things aren't properly filled. How would I go about trying to fix this mapping issue? Is it even possible to reference a Director's Cut through tvdb api?

I do have a custom mapping for the specials, so that anidb Special 01 links directly to tvdb Special 01, and not to Special 2 and so on, as is the case by default. I removed the custom mapping so as not to alter any of the logs:

[Re Zero kara Hajimeru Isekai Seikatsu [anidb-11370].scanner.log](https://github.com/ZeroQI/Hama.bundle/files/5898014/Re.Zero.kara.Hajimeru.Isekai.Seikatsu.anidb-11370.scanner.log)
[Re Zero kara Hajimeru Isekai Seikatsu [anidb-11370].agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/5898015/Re.Zero.kara.Hajimeru.Isekai.Seikatsu.anidb-11370.agent-update.log)
[Re Zero kara Hajimeru Isekai Seikatsu [anidb-11370].filelist.log](https://github.com/ZeroQI/Hama.bundle/files/5898016/Re.Zero.kara.Hajimeru.Isekai.Seikatsu.anidb-11370.filelist.log)

Any input would be appreciated.

Thanks!

**Comment by ZeroQI** [comment] 2021-01-30 14:56
In TheTVDB, the director's cut are only supported in an alternate order, not showing as specials so not supported
For AniDB, the numbering is correct and episodes detected, albeit with no title (implied: for the selected language, which for you are set in settings to: ['ja', 'en'])
```
 [X] s0e401 => s0e401 air_date: 2020-01-01 language_rank: 0, title: ""
 - [ ] summary: Natsuki Subaru is summoned to a parallel world on his way home from the convenience store. He's entranced at first by the fantasy world 
```

The AniDB API url is listed above:`common.LoadFile() - File cached locally - Filename: 'AniDB\xml\11370.xml', Age: '0.02 days', Limit: '318 days', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11370'`

Please check the cached file  'AniDB\xml\11370.xml' in agent data folder match the details for episode O1:

```
<episode id="225905" update="2020-02-26">
<epno type="6">O1</epno>
<length>55</length>
<airdate>2020-01-01</airdate>
<rating votes="3">9.29</rating>
<title xml:lang="ja">始まりの終わりと終わりの始まり</title>
<title xml:lang="en">Director`s Cut: The End of the Beginning and the Beginning of the End</title>
<title xml:lang="x-jat">Hajimari no Owari to Owari no Hajimari</title>
<summary>Natsuki Subaru is summoned to a parallel world on his way home from the convenience store. He`s entranced at first by the fantasy world suddenly stretching before his eyes, but the cute girl he believes summoned him is nowhere to be found, and soon enough he`s utterly lost. Then a gang of punks surrounds him, but he quickly learns that he doesn`t have any of the powers that he thought all people transported to a parellel world should have. Just when he`s about to be beaten senseless, a girl appears... Source: crunchyroll</summary>
<resources>
<resource type="28">
<externalentity>
<identifier>792278</identifier>
<identifier>rezero-starting-life-in-another-world-</identifier>
</externalentity>
</resource>
</resources>
</episode>
```

if it is matching, it should have matched the JAP title with language_rank 0 and as fallback the En title with language_rank 1 and code would need editing

**Comment by koalix** [comment] 2021-01-30 14:59
Mine is mapping perfectly. Here is how I did:

 

Directory of G:\(...)\ReZero kara Hajimeru Isekai Seikatsu [anidb2-11370]

 

11/06/2020  08:53    <DIR>          .

11/06/2020  08:53    <DIR>          ..

21/12/2020  00:58       306.153.217 [EA]Re_Zero_-_Director's_Cut_O1_[1280x720][Hi10p][746099A2].mkv

21/12/2020  00:58       291.605.815 [EA]Re_Zero_-_Director's_Cut_O3_V2_[1280x720][Hi10p][DD529B9B].mkv

21/12/2020  00:58       348.446.671 [EA]Re_Zero_-_Director's_Cut_O9_[1280x720][Hi10p][69267CBC].mkv

21/12/2020  00:58       319.759.272 [EA]Re_Zero_-_Director's_Cut_O5_[1280x720][Hi10p][D3E8CAB1].mkv

21/12/2020  00:58       444.647.864 [EA]Re_Zero_-_Director's_Cut_O11_[1280x720][Hi10p][38ECE234].mkv

21/12/2020  00:58       436.405.694 [EA]Re_Zero_-_Director's_Cut_O10_[1280x720][Hi10p][CDCDA606].mkv

21/12/2020  00:58       349.505.300 [EA]Re_Zero_-_Director's_Cut_O2_[1280x720][Hi10p][EB7F1E55].mkv

21/12/2020  00:58       476.109.564 [EA]Re_Zero_-_Director's_Cut_O6_[1280x720][Hi10p][7C5D4689].mkv

21/12/2020  00:58       536.985.139 [EA]Re_Zero_-_Director's_Cut_O13_Final_[1280x720][Hi10p][3FE75E96].mkv

21/12/2020  00:58       406.323.968 [EA]Re_Zero_-_Director's_Cut_O4_[1280x720][Hi10p][91666A40].mkv

21/12/2020  00:58       347.682.270 [EA]Re_Zero_-_Director's_Cut_O7_[1280x720][Hi10p][F34F5607].mkv

21/12/2020  00:58       385.429.967 [EA]Re_Zero_-_Director's_Cut_O12_[1280x720][Hi10p][846A5C18].mkv

21/12/2020  00:58       393.672.208 [EA]Re_Zero_-_Director's_Cut_O8_[1280x720][Hi10p][883441C0].mkv

**Comment by ZeroQI** [comment] 2021-01-30 15:08
https://github.com/Anime-Lists/anime-lists/blob/master/anime-list-master.xml
```
  <anime anidbid="11370" tvdbid="305089" defaulttvdbseason="1" episodeoffset="" tmdbid="" imdbid="">
    <name>Re:Zero kara Hajimeru Isekai Seikatsu</name>
    <mapping-list>
      <mapping anidbseason="0" tvdbseason="0">;1-0;</mapping>
      <mapping anidbseason="0" tvdbseason="0" start="2" end="26" offset="-1"/>
    </mapping-list>
```

Anidb2 map to thetvdb numbering so unsure which ep it get maps to and if the metadata is the director's cut or the standard season 1, as the mapping file do not map the other episodes...

**Comment by jvmunhoz** [comment] 2021-01-30 16:30
> In TheTVDB, the director's cut are only supported in an alternate order, not showing as specials so not supported
> For AniDB, the numbering is correct and episodes detected, albeit with no title (implied: for the selected language, which for you are set in settings to: ['ja', 'en'])
> 
> ```
>  [X] s0e401 => s0e401 air_date: 2020-01-01 language_rank: 0, title: ""
>  - [ ] summary: Natsuki Subaru is summoned to a parallel world on his way home from the convenience store. He's entranced at first by the fantasy world 
> ```
> 
> The AniDB API url is listed above:`common.LoadFile() - File cached locally - Filename: 'AniDB\xml\11370.xml', Age: '0.02 days', Limit: '318 days', url: 'http://api.anidb.net:9001/httpapi?request=anime&client=hama&clientver=1&protover=1&aid=11370'`
> 
> Please check the cached file 'AniDB\xml\11370.xml' in agent data folder match the details for episode O1:
> 
> ```
> <episode id="225905" update="2020-02-26">
> <epno type="6">O1</epno>
> <length>55</length>
> <airdate>2020-01-01</airdate>
> <rating votes="3">9.29</rating>
> <title xml:lang="ja">始まりの終わりと終わりの始まり</title>
> <title xml:lang="en">Director`s Cut: The End of the Beginning and the Beginning of the End</title>
> <title xml:lang="x-jat">Hajimari no Owari to Owari no Hajimari</title>
> <summary>Natsuki Subaru is summoned to a parallel world on his way home from the convenience store. He`s entranced at first by the fantasy world suddenly stretching before his eyes, but the cute girl he believes summoned him is nowhere to be found, and soon enough he`s utterly lost. Then a gang of punks surrounds him, but he quickly learns that he doesn`t have any of the powers that he thought all people transported to a parellel world should have. Just when he`s about to be beaten senseless, a girl appears... Source: crunchyroll</summary>
> <resources>
> <resource type="28">
> <externalentity>
> <identifier>792278</identifier>
> <identifier>rezero-starting-life-in-another-world-</identifier>
> </externalentity>
> </resource>
> </resources>
> </episode>
> ```
> 
> if it is matching, it should have matched the JAP title with language_rank 0 and as fallback the En title with language_rank 1 and code would need editing

Yes, first thing I did was check the 11370.xml. All informations regarding the Director's Cut was there. Here it is:


[11370.zip](https://github.com/ZeroQI/Hama.bundle/files/5898237/11370.zip)


> Mine is mapping perfectly. Here is how I did: Directory of G:\(...)\ReZero kara Hajimeru Isekai Seikatsu [anidb2-11370] 11/06/2020 08:53 <DIR> . 11/06/2020 08:53 <DIR> .. 21/12/2020 00:58 306.153.217 [EA]Re_Zero_-_Director's_Cut_O1_[1280x720][Hi10p][746099A2].mkv 21/12/2020 00:58 291.605.815 [EA]Re_Zero_-_Director's_Cut_O3_V2_[1280x720][Hi10p][DD529B9B].mkv 21/12/2020 00:58 348.446.671 [EA]Re_Zero_-_Director's_Cut_O9_[1280x720][Hi10p][69267CBC].mkv 21/12/2020 00:58 319.759.272 [EA]Re_Zero_-_Director's_Cut_O5_[1280x720][Hi10p][D3E8CAB1].mkv 21/12/2020 00:58 444.647.864 [EA]Re_Zero_-_Director's_Cut_O11_[1280x720][Hi10p][38ECE234].mkv 21/12/2020 00:58 436.405.694 [EA]Re_Zero_-_Director's_Cut_O10_[1280x720][Hi10p][CDCDA606].mkv 21/12/2020 00:58 349.505.300 [EA]Re_Zero_-_Director's_Cut_O2_[1280x720][Hi10p][EB7F1E55].mkv 21/12/2020 00:58 476.109.564 [EA]Re_Zero_-_Director's_Cut_O6_[1280x720][Hi10p][7C5D4689].mkv 21/12/2020 00:58 536.985.139 [EA]Re_Zero_-_Director's_Cut_O13_Final_[1280x720][Hi10p][3FE75E96].mkv 21/12/2020 00:58 406.323.968 [EA]Re_Zero_-_Director's_Cut_O4_[1280x720][Hi10p][91666A40].mkv 21/12/2020 00:58 347.682.270 [EA]Re_Zero_-_Director's_Cut_O7_[1280x720][Hi10p][F34F5607].mkv 21/12/2020 00:58 385.429.967 [EA]Re_Zero_-_Director's_Cut_O12_[1280x720][Hi10p][846A5C18].mkv 21/12/2020 00:58 393.672.208 [EA]Re_Zero_-_Director's_Cut_O8_[1280x720][Hi10p][883441C0].mkv

Tried changing to anibd2 but everything remains the same:

They remains os Other 01...13 in the Specials season

![image](https://user-images.githubusercontent.com/42040576/106361886-966eef80-62fe-11eb-9544-319d0f823a06.png)

**Comment by EndOfLine369** [comment] 2021-01-30 16:51
Looks like you have zero languages set in HAMA for "Serie Language Priority" or "Episode Language Priority"
`TVDBid: '305089', IMDbid: '', language_series : [], language_episodes: []`

And you're only getting titles from TVDB on the other episodes as we force in an english default at the end of the priority list.

**Comment by jvmunhoz** [comment] 2021-01-30 17:09
Ok, that was dumb. I had both settings as "main".

I had noticed I was getting all episode name metadata from TVDB but I guessed that's how HAMA worked, since I'm new to it.

Now I just need to see if there is a way to map these episodes to Season 1 instead of Others lol

Thanks for the fix :D

**Comment by EndOfLine369** [comment] 2021-01-30 17:28
I don't think you're going to be able to get what you want to get. Which I think is those "Director Cut" episodes as S1 with metadata. To my knowledge, we mainly only support TVDB's aired order (standard/legacy), transposing absolute order to aired ordered placement, & reordering based on actual air date. None of which would get this out of S0 "Other" status with metadata being available.

**Comment by ZeroQI** [comment] 2021-01-30 17:36
Or absolute numbering with tvdb 3/4 modes...

**Comment by EndOfLine369** [comment] 2021-01-30 17:40
> Or absolute numbering with tvdb 3/4 modes...

To clarify:
tvdb2/3 are the "transposing absolute order to aired ordered placement" I mentioned
tvdb4 is "transposing absolute order to custom season placement" which I didn't mention
Both of which would still not help in moving out of S0 "Other" status with metadata being available. (again to my knowledge)

**Comment by EndOfLine369** [comment] 2021-01-30 17:54
Since the 'issue' is fixed with root cause being incorrect "Serie Language Priority" & "Episode Language Priority" entries I think this can now be closed out. Any further testing you do to try to get the custom mapping goal via different modes w/ possibly mapping hacks via a local 'anime-list-custom.xml' file are not an issue/bug for HAMA to be looked into.

**Comment by jvmunhoz** [comment] 2021-01-30 18:06
Well, [I actually managed to do it](https://user-images.githubusercontent.com/42040576/106364196-ffa92f80-630b-11eb-85d1-0b5dfbd85d4e.png) by manually editing the 11370.xml and replacing episodes 1-13 matadata with the ones from the Director's Cut version. Brute force, sure, but probably the only way to do it. 

A custom-mapping scheme for cases such as this when you would like to make a custom order would be a nice addition. Specials counting as an extra episode is pretty common in anime.

And thanks again for the help, had no idea could be my configs...

You may close the issue.

**Comment by ZeroQI** [comment] 2021-01-30 20:22
Normally the custom mapping file would do the trick but NOT for alternate tvdb numbering like there's so yes that is the only back possible.

Yes tvdb34 would not solve neither

**Closed by ZeroQI** 2021-01-30 20:22 UTC
