### ISSUE TITLE
not downloading metadata for series?

### ISSUE THREAD

**Issue by squeekr** [ZeroQI/Hama.bundle#317] opened 2019-05-22 11:02 UTC
so i actually misidentified an issue earlier, here is an updated log. when i have it find a match in plex through hamatv agent, everything blanks out (no cover art, episode info, etc.)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3207043/com.plexapp.agents.hama.log)

**Comment by ZeroQI** [comment] 2019-05-22 21:35
AttributeError: 'str' object has no attribute 'xpath'
Download and replace manually anime-titles.xml in agent data folders / AniDB like everybody else impacted in the forum. See my last post now:
https://forums.plex.tv/t/rel-http-anidb-metadata-agent-hama/40470/1897?u=zeroqi
Closing as duplicate of https://github.com/ZeroQI/Hama.bundle/issues/309

**Closed by ZeroQI** 2019-05-22 21:35 UTC

**Comment by DarthKnight12** [comment] 2019-05-25 11:28
hi,

i still don't know what is happening at my end, but i have tried multiple things now:

1) deleted anime-titles.xml
2) deleted HAMA and ASS
3) Reinstalled Hama and ASS
4) after inital scan, deleted anime-titles.xml everywhere and replaced it with the provided version.

Still i have multiple shows that just refuse to load/show/fetch metadata and are left completely blank. Im slowly but surely losing my mind

log (with the relevant info):

[com.plexapp.agents.hama_relevantinfo.log](https://github.com/ZeroQI/Hama.bundle/files/3219336/com.plexapp.agents.hama_relevantinfo.log)
