### ISSUE TITLE
HAMA Log Improvements

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#72] opened 2016-08-01 03:48 UTC
A few things on the Logs:

1.  If something shows up in one of the logs, let's say you start watching a show, don't like it, and delete it, but if there were any missing episodes (or anything that triggers a line in the log), they will not be deleted.  I regularly delete my HAMA logs and run a full refresh, but I've noticed this popping up.  I don't think this is a bad thing.  Especially if I'm moving things in and out of the library for testing/cleaning/etc...

2.  This might be too much, but you'll notice the logs will have a TON of missing episodes if TVDB or AniDB has populated the shows out in advance.  I feel like it tends to be a little misleading.  Is there any way we could have those marked as unaired?  Most things in my log, I'm not actually missing.  They just don't exist yet.  We should have access to the airdate, I would think.

<img width="872" alt="screen shot 2016-07-31 at 11 47 13 pm" src="https://cloud.githubusercontent.com/assets/18091557/17282936/1ff9b014-5779-11e6-8b01-150daf226d18.png">

3.  AniDB lines seem to be reverse numerical/alphabetical in their lines.  TVDB all seem to be fine.

**Comment by EndOfLine369** [comment] 2016-08-02 02:13
1) Don't think it is doable. I also have this issue as I start some new series but then decide to remove it as it turns out I hate it. The problem is that we could add a timestamp to the log of when it was last updated but that would not help as only series refreshed would get updated in the log with a new timestamp. We also can't check other series other then the one being refreshed as the media info provided (including part/file location) is only for the series being refreshed.

2) Seems doable. We can probably just check if the curr date > air date + 1 (if air date exists).

3) Seems doable. Its because of the episode order provided by the APIs. We would have to sort the list after generation but before printing to the log.

**Comment by EndOfLine369** [comment] 2016-08-02 02:19
@ZeroQI, for number 1 do we want to start storing the media info (series id/ep num/files) into the HAMA data directory? If we do, we can start referencing seriesX file info outside a seriesY update.

**Comment by ZeroQI** [comment] 2016-08-02 03:15
@sven-7: 1) you can delete logs since you run a full update afterwards... Don't see any need for change there
@EndOfLine369: 1) the logs just does that.
2) yep seem good
3) agreed.

**Comment by EndOfLine369** [comment] 2016-08-02 05:29
(3) has been committed

**Comment by EndOfLine369** [comment] 2016-08-02 08:00
(2) has been committed

**Comment by EndOfLine369** [comment] 2016-08-02 08:05
EX Log statements.
TVDB ID:
```
2016-08-02 02:48:00,014 - com.plexapp.agents.hama (-b484470) : INFO (__init__/Update:641) - abs_manual_placement_worked: 'True', abs_manual_placement_info: '[]'
2016-08-02 02:48:01,677 - com.plexapp.agents.hama (-b484470) : WARNING (__init__/Update:641) - Episode '470' is missing in Plex but air date '20160804+1' is either missing (99999999) or in the future
2016-08-02 02:48:01,678 - com.plexapp.agents.hama (-b484470) : DEBUG (__init__/Update:641) - TVDB - Episodes with Summary: ['1', '10', '100', '101', '102', '103', '104', '105', '106', '107', '108', '109'...
```
AniDB ID:
```
2016-08-02 02:40:05,641 - com.plexapp.agents.hama (-b484470) : INFO (__init__/Update:641) - AniDB specials title - Season: '0', epNum.text: 'C1', epNumVal: '101', ep_title: 'Opening'
2016-08-02 02:40:05,643 - com.plexapp.agents.hama (-b484470) : WARNING (__init__/Update:641) - Episode '8' is missing in Plex but air date '20160819+1' is either missing (99999999) or in the future
2016-08-02 02:40:05,644 - com.plexapp.agents.hama (-b484470) : WARNING (__init__/Update:641) - Episode '7' is missing in Plex but air date '20160812+1' is either missing (99999999) or in the future
2016-08-02 02:40:05,645 - com.plexapp.agents.hama (-b484470) : WARNING (__init__/Update:641) - Episode '6' is missing in Plex but air date '20160805+1' is either missing (99999999) or in the future
2016-08-02 02:40:05,647 - com.plexapp.agents.hama (-b484470) : INFO (__init__/Update:641) - AniDB episode title: 'Tower of Conviction'*
```

**Comment by ZeroQI** [comment] 2016-08-02 11:04
@EndOfLine369 Nice :D

**Closed** 2016-08-03 01:08 UTC
Labels: enhancement

**Comment by sven-7** [comment] 2016-08-03 01:15
Nice!!

Will test soon. Thanks! 😬😉🍺

**Comment by sven-7** [comment] 2016-08-03 14:18
I'm not having any of the HAMA htm logs generate now.  I've done two full refreshes (with an intentional missing episode) and nothing has popped up.

**Comment by EndOfLine369** [comment] 2016-08-03 15:37
Sounds like a problem on your end as neither my my changes touched anything related to the file generation. Only the data in 4 of them. Please make sure all your Hama files are up-to-date.

**Comment by EndOfLine369** [comment] 2016-08-03 15:45
If after updating your files and it still does not run, will need to see your hama log.

**Comment by sven-7** [comment] 2016-08-03 19:01
I had not replaced the .json.  (I typically only replace the .py) 

Thanks!
