### ISSUE TITLE
AniDB 3/4 mode season summary

### ISSUE THREAD

**Issue by sven-7** [ZeroQI/Hama.bundle#354] opened 2019-10-12 17:01 UTC
Would it be possible when using AniDB 3/4 to have the season summary metadata field populate with the summary for the AniDB associated with it?

E.g. Sword Art Online II for season 2

> A year has passed since Sword Art Online (SAO) was cleared. Kirito is asked by Kikuoka to investigate Gun Gale Online, specifically Death Gun, a weapon which seemed to link deaths in the virtual reality world to those in the real world.
> 
> Upon entering the game, Kirito meets Sinon who teaches him the ropes of the game. They both enter the Gun Gale Online tournament, Bullet of Bullets. Kirito displays his amazing skills although he is only a newcomer to the game. Later, Kirito finds out that the mysterious deaths are linked to a red guild named Laughing Coffin in SAO.

<img width="723" alt="Screen Shot 2019-10-12 at 12 59 57 PM" src="https://user-images.githubusercontent.com/18091557/66705073-3959bf80-ecf0-11e9-9c2c-f8042e8b3587.png">

**Comment by ZeroQI** [comment] 2019-10-12 19:31
Would need to try to populate the field in the dict and see if it updates, then put the right summary in it if it works.

**Comment by sven-7** [comment] 2019-10-12 19:33
Would be a really cool feature if it does. The season summary field is tragically ignored and underused.

**Comment by EndOfLine369** [comment] 2019-10-12 21:34
@ZeroQI, we already set this on seasons.
https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AniDB.py#L175

Granted, it looks like the if condition is incorrect so it will only put in s1 summary for the anime on that season for non-anidb_numbering entries.

It does not go through into Plex.
```
metadata.seasons[ 1]--------------------------------------------------------------------------------------------------------------------------------------
[=] summary                        Sources: (AniDB), TheTVDB                                              Inside: '[]'  Value: 'Kazuto "Kirito" Kirigaya enters a virtual-reality, massively multiplayer online ..'
```
![image](https://user-images.githubusercontent.com/16750699/66707930-3077e680-ed0e-11e9-9715-71ce2e8790f8.png)

**Comment by EndOfLine369** [comment] 2019-10-12 21:50
So same as original_title. We can set it but Plex will not load it. Not possible per them [HERE](https://forums.plex.tv/t/bug-report-unable-to-update-original-title-in-tv-show-and-season-summary/183240/14).

Season summary would be nice but as same sitch as orig_title, doubt it will get working any time soon. I would personally love to see a custom season title in addition to the summary working.

Based on their updates, they are more focused on new features to gather new users than enhancing existing/core setups like this.

**Comment by sven-7** [comment] 2019-10-12 21:58
Ah bummer. Thanks for the info. 

Definitely agree with you on modifying season title. I’ve seen it done by editing one of the web client plugins and adding the field in the code...but doubt they’ll formalize that. 

I’ll close this as nothing can be done for now.

**Comment by ZeroQI** [comment] 2019-10-12 22:24
From my work on Lambda, there might be a way to upload directly to Plex database, not the framework way. Reopening so I remember to check

**Comment by ZeroQI** [comment] 2020-03-18 02:48
From Lambda code, to be tested
That's the normal summary but we may update the season summary maybe with it
```
PMS                             = 'http://127.0.0.1:32400'  # Since PMS is hardcoded to listen on 127.0.0.1:32400, that's all we need
PMSLIB                          = PMS + '/library'
PMSSEC                          = PMSLIB + '/sections'
PLEX_UPLOAD_TEXT                = PMSSEC + '/{}/all?type=18&id={}&summary.value={}'
r = HTTP.Request(PLEX_UPLOAD_TEXT.format(key, ratingKey, String.Quote(Core.storage.load(destination))), headers=HEADERS, method='PUT')
      Log.Info('request content: {}, headers: {}, load: {}'.format(r.content, r.headers, r.load))
```

**Comment by ZeroQI** [comment] 2021-02-26 23:56
Closing this request as a duplicate of https://github.com/ZeroQI/Hama.bundle/issues/452

**Closed by ZeroQI** 2021-02-26 23:56 UTC
Labels: enhancement
