### ISSUE TITLE
Not Adding Posters

### ISSUE THREAD

**Issue by SaltSouls** [ZeroQI/Hama.bundle#304] opened 2019-05-02 22:36 UTC
When adding a new series I have noticed that it isn't auto adding the poster from either Anidb or any other sites. I had to recently download the latest version when the last version suddenly stopped being able to match series, and since then it hasn't been able to add the posters.
EDIT: Yes I also did update to the latest ASS and the problem still persists. I gets the episode renaming and what not but it isn't adding the posters to the show. I have even found where it is downloading them to, but it isn't auto adding them to the series.

My HamaTV Log:
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3140329/com.plexapp.agents.hama.log)

Series Log: [Poster won't add to this series]
[Saishuu Chikan Densha NEXT.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3140345/Saishuu.Chikan.Densha.NEXT.agent-update.log)

**Comment by MrPiethon** [comment] 2019-05-03 22:23
It says you are banned from anidb. I wonder if that is the issue.

I am also having the same problems. Titles are renamed. Some covers/meta have been loaded (3/451). Checking my logs, I can also see that I have been banned from anidb.

**Comment by SaltSouls** [comment] 2019-05-03 22:29
Yeah I had noticed that but the strange thing is that I don't know if I was IP banned, MAC banned or account banned. In reality none of those would make sense as my account is still active and I can still go on their website no problem. Not sure what is causing the ban error.

**Comment by ZeroQI** [comment] 2019-05-03 22:31
[x] posters                  ( 1)  Sources: tvdb4, TheTVDB, TheMovieDb, FanartTV, (AniDB)                 Inside: '['AniDB']'  Value: '{'http://img7.anidb.net/pics/anime/87605.jpg': (u'AniDB\\poster\\87605.jpg', 25, 'http://img7.anidb.net/pics/anime/thumbs/150/87605.jpg-thumb.jpg')}'
common.SaveFile() - Exception: HTTP Error 403: Forbidden, url: 'http://img7.anidb.net/pics/anime/87605.jpg', filename: 'AniDB\poster\87605.jpg'

you do not have the http right to download the file, you are confirmed banned accessing metadata, not the website
possibly downloaded twice the title database in a day or too many requests in a short time...

**Comment by SaltSouls** [comment] 2019-05-03 22:38
I wonder if there is a way to get around this, as it is a huge inconvenience for anyone that may be faced with a similar issue.

**Comment by MrPiethon** [comment] 2019-05-03 22:41
There is: you can download a VPN and change your IP location I believe.

**Comment by SaltSouls** [comment] 2019-05-03 22:43
> 
> 
> There is: you can download a VPN and change your IP location I believe.

While I would love to as that might just work, it completely breaks Plex and I have not found a reliable way to get around that. Also, how do I get the metadata for the rest of the show but not the poster? Is the process for the two different, because I believed that it all fell under metadata.

**Comment by MrPiethon** [comment] 2019-05-03 22:45
I am not sure. I only am able to rename the titles into Japanese. Meta data including summaries, posters, etc are not working for me atm most likely cause I have already been banned from anidb,

**Comment by SaltSouls** [comment] 2019-05-03 22:50
For me they are working just fine after updating everything. If I go to the site I can still see and access all metadata. It still correctly places it into my Plex series and it has the correct numbers for the images if downloaded(Just tested on the site and I can still manually download them no problem. Not sure what HamaTV is doing to download series images, but the image name and everything is the same as in the log file.) onto my PC in the log file. Also, some of the images I have found on my PC already, but it just refuses to add them to Plex. the log file I provided is one such instance that I have it on my PC but it is not using said image as the series image.

**Comment by MrPiethon** [comment] 2019-05-03 23:10
@ZeroQI If those image ids refers to the actual series title, wouldn't it be better to include a folder of series images already pre-compiled? Then if a series matches up with the corresponding id, it would grab the cover automatically.

I wonder if we can do this for meta data as well (title, summary, etc)

**Comment by ZeroQI** [comment] 2019-05-03 23:17
if it downloaded ok, then plex is not updating
Do the Plex Dance (r)

**Comment by SaltSouls** [comment] 2019-05-03 23:20
@ZeroQI I have updated and restarted my Plex serveral times to try and fix this. Yet nothing has worked. It updated the basic metadata for the series and added everything but the poster. When I retried today it still didn't add the posters in. That is the only thing I am currently seeing as being broken.

**Comment by ZeroQI** [comment] 2019-05-03 23:21
when you open the poster url in the end of the series log from the plex server machine, do they work?
wait 24h since banned otherwise

**Comment by SaltSouls** [comment] 2019-05-03 23:26
They seem to currently work for me, but it still isn't adding the posters.

**Comment by ZeroQI** [comment] 2019-05-03 23:31
HTTP Error 403 may be given by plex. check agent data folder permissions update plex, clean bundles

**Comment by SaltSouls** [comment] 2019-05-03 23:38
A bit confused on what exactly you mean. Not sure what you mean by check the permissions of the folder(do you mean the "com.plexapp.agents.hama" folder?) as in actually go in and check if it has the option to be edited or make edits. If so then it has full perms. Then I don't know what you mean by bundles. Like not even in the slightest.

**Comment by ZeroQI** [comment] 2019-05-03 23:42
i believe only you have that issue.
there is a ban, this needs solving.
there is an http error so a web server is refusing to let download the file so it is consistent. wait 24 hours and try again

https://support.plex.tv/articles/200392106-library-actions/
- empty trash
- clean bundles
- optimize database

**Comment by SaltSouls** [comment] 2019-05-03 23:44
@ZeroQI Thanks. I actually didn't know that Plex had said features. Probably would have tried this frist had I known.

**Comment by EndOfLine369** [comment] 2019-05-05 06:29
Pull fresh from HAMA master. 
I had same issue. Should now be fixed in https://github.com/ZeroQI/Hama.bundle/commit/1ce898cfc5e90665a2274eaa32b744914d5876fc
Second thing AniDB seems to have changed without notice.

**Closed** 2019-05-05 12:00 UTC
