### ISSUE TITLE
References TheTVDB instead of AniDB for some seasons/specials

### ISSUE THREAD

**Issue by stevenx37** [ZeroQI/Hama.bundle#358] opened 2019-10-25 03:43 UTC
New bug introduced by @EndOfLine369's latest commits, which seem to affect which source Hama decides to pull episodes from (either AniDB/TheTVDB?).
I'm having issues with Monogatari, where every off-season/"special" series uses [TheTVDB's listing](https://www.thetvdb.com/series/monogatari/seasons/0) with absolute numbering instead of originally using AniDB's listing with absolute numbering [(e.g. Kizumonogatari)](https://anidb.net/anime/8357). 
This means in Plex, all of the series below use TheTVDB, so they all have the exact same episodes listed (and all the relevant metadata) up to their respective episode count:
Tsukimonogatari, Nekomonogatari (Kuro), Kizumonogatari, and Hanamonogatari

Edit: Ok using the version before the commits, all the episodes are labelled and dated correctly, but Hama takes episode thumbnails and summaries from [TheTVDB](https://www.thetvdb.com/series/monogatari/seasons/0) using absolute numbering. So those four series all have the same episode thumbnails and summaries.

Also, I am using the default settings for Hama.

**Comment by EndOfLine369** [comment] 2019-10-25 04:56
Logs w/exact example. But sounds like you had something working that should have with mention of "TVDB absolute numbering" usage.

**Comment by ZeroQI** [comment] 2019-10-25 05:20
Do you have more than 1 season picked by scanner for the series?
if so it will match the series id to tvdb and use thetvdb specials numbering but still cross referencing thetvdb and anidb...

The way you explain it, it seems you follow anidb numbering but quote a series with no specials mentioning specials comes from thetvdb, so as clear as mud i am afraid...

Without logs, impossible to see. Please attach logs located in agent data folders for the series involved

**Comment by stevenx37** [comment] 2019-10-25 18:29
Ok. Just this log?
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/3773287/com.plexapp.agents.hama.log)

**Comment by ZeroQI** [comment] 2019-10-25 18:36
No.

[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/(Library_name/)series_root_folder.agent-search.log (guid assignment)
[...]/Plex Media Server/Plug-in Support/Data/com.plexapp.agents.hama/DataItems/_Logs/(Library_name/)series_root_folder.agent-update.log (metadata update)

**Comment by stevenx37** [comment] 2019-10-25 18:44
[_unknown_folder.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3773324/_unknown_folder.agent-update.log)
[_unknown_folder.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/3773325/_unknown_folder.agent-search.log)

**Comment by stevenx37** [comment] 2019-10-25 20:13
Forgot to link some screenshots, if it helps. I had some start with episode 2 to match AniDB's episode titles.
![Annotation 2019-10-25 160845](https://user-images.githubusercontent.com/15038615/67601294-ff51da00-f741-11e9-843e-65b03e83ad4f.jpg)
![Annotation 2019-10-25 160815](https://user-images.githubusercontent.com/15038615/67601295-ff51da00-f741-11e9-80f2-21e6c68de9f8.jpg)
![Annotation 2019-10-25 160756](https://user-images.githubusercontent.com/15038615/67601296-ff51da00-f741-11e9-839c-9fa04023896f.jpg)
![Annotation 2019-10-25 160717](https://user-images.githubusercontent.com/15038615/67601297-ffea7080-f741-11e9-9328-394fcd51bfc4.jpg)

**Comment by EndOfLine369** [comment] 2019-10-26 02:07
I have no idea how 76 update runs got in that single Frankenstein update file. It is unreadable. Please provide a single series refresh log for each of the two you showed above.

**Comment by stevenx37** [comment] 2019-10-26 02:20
I'm assuming the same _Logs folder?
[Hanamonogatari - Suruga Devil (TV Special).filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3774345/Hanamonogatari.-.Suruga.Devil.TV.Special.filelist.log)
[Hanamonogatari - Suruga Devil (TV Special).scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3774346/Hanamonogatari.-.Suruga.Devil.TV.Special.scanner.log)
[Kizumonogatari.filelist.log](https://github.com/ZeroQI/Hama.bundle/files/3774347/Kizumonogatari.filelist.log)
[Kizumonogatari.scanner.log](https://github.com/ZeroQI/Hama.bundle/files/3774348/Kizumonogatari.scanner.log)

**Comment by EndOfLine369** [comment] 2019-10-26 02:59
perfect. all those

**Comment by EndOfLine369** [comment] 2019-10-26 03:20
For Kizumonogatari, looks like its an issue in AnimeList mapping in HAMA. It is behaving correctly with the mapping is is using (granted its incorrect/incomplete mapping). So the issue is seen. Need to find the cause for the incorrect processing of the 'mapping-list' entries.
```
===== Scanner =====

"Kizumonogatari" s01e001                         "Word Search" "Iron-Blooded" "[Edo] Kizumonogatari 01 - Iron-Blooded [1080].mkv"
"Kizumonogatari" s01e002                         "Word Search" "Hot-Blooded" "[Edo] Kizumonogatari 02 - Hot-Blooded [1080].mkv"
"Kizumonogatari" s01e003                         "Word Search" "Cold-Blooded" "[Edo] Kizumonogatari 03 - Cold-Blooded [1080].mkv"

===== HAMA =====
=== Update() ================================================================================================================================================
id: anidb-8357, title: Kizumonogatari, lang: en, force: True, movie: False
start: 2019-10-25 14:20:39,820000
=== AnimeLists.GetMetadata() ================================================================================================================================
tvdb_numbering: False
Local custom mapping file not present: anime-list-custom.xml
--- AniDBTVDBMap --------------------------------------------------------------------------------------------------------------------------------------------
[+] AniDBid:  8357, TVDBid: 102261, defaulttvdbseason:   0, offset:   0, name: Kizumonogatari
             -----          ------
              8357          102261
...
...
=== TheTVDB.GetMetadata() ===================================================================================================================================
TVDBid: '102261', IMDbid: 'tt3138698,tt5084196,tt5084198', language_series : ['en', 'ja'], language_episodes: ['en', 'ja']
...
...
--- episodes ------------------------------------------------------------------------------------------------------------------------------------------------
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/series/102261/episodes?page=1', Filename: 'TheTVDB/json/102261\episodes_page1_en.json', Age: '56305.8267446', Ended: None
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/series/102261/episodes?page=2', Filename: 'TheTVDB/json/102261\episodes_page2_en.json', Age: '56305.4580956', Ended: None
[X]    s0e1 s01e001 anidbid:         air_date: 2009-08-07 abs_number: 0, title: Episode 5.5 (Recap)
 - [1] title:   [en] Episode 5.5 (Recap)
 - [1] summary: [en] A recap of episodes 1-5 of Bakemonogatari.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/3406651', Filename: 'TheTVDB/json/102261\episode_3406651_ja.json', Age: '56304.6297386', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/102261/3406651.jpg
[X]    s0e2 s01e002 anidbid:         air_date: 2016-01-08 abs_number: 0, title: Kizumonogatari I: Iron Blood Arc
 - [1] title:   [en] Kizumonogatari I: Iron Blood Arc
 - [1] summary: [en] I think it's about time I talked about Kiss-Shot-Acerola-Orion Heart-Under-Blade. I believe it's something I have to do. I met her in the spring break between my second and third years of high school. That meeting had such impact, and was also quite devastating.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4139150', Filename: 'TheTVDB/json/102261\episode_4139150_ja.json', Age: '56305.1597226', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/102261/4139150.jpg
[X]    s0e3 s01e003 anidbid:         air_date: 2012-12-31 abs_number: 0, title: Tsubasa Family - Part 1
 - [1] title:   [en] Tsubasa Family - Part 1
 - [1] summary: [en] Koyomi Araragi begins the day by being rudely awoken by his sister, Tsukihi. He decides to discuss love with her, asking how one can tell if they are in love or not. It turns out that recently, he can't stop thinking about his classmate, Hanekawa Tsubasa. Later, he runs into Hanekawa, who reveals a shocking fact which he may not tell anyone else about.
common.LoadFile() - File cached locally - url: 'https://api.thetvdb.com/episodes/4450835', Filename: 'TheTVDB/json/102261\episode_4450835_ja.json', Age: '56304.8257337', Ended: None
 - [ ] thumb: https://thetvdb.plexapp.com/banners/episodes/102261/4450835.jpg
...
...
=== AniDB.GetMetadata() =====================================================================================================================================
Source: anidb, AniDBid: 8357, Full AniDBids list: ['8357'], Active AniDBids list: ['8357']
...
...
--- 8357.episodes -------------------------------------------------------------------------------------------------------------------------------------------
[ ] ep creators (creators tag): {'producers': ['Shinbou Akiyuki', 'Tou Fuyashi'], 'directors': ['Oishi Tatsuya'], 'writers': ['Nishio Ishin']}
[X] s1e  1 => s1e  1 air_date: 2016-01-08 language_rank: 1, title: "Iron-Blooded Arc"
 - [ ] summary: 
[X] s1e  2 => s1e  2 air_date: 2016-08-19 language_rank: 1, title: "Hot-Blooded Arc"
 - [ ] summary: 
[X] s1e  3 => s1e  3 air_date: 2017-01-06 language_rank: 1, title: "Cold-Blooded Arc"
 - [ ] summary: 
...
...
metadata.seasons[ 1]--------------------------------------------------------------------------------------------------------------------------------------
metadata.seasons[ 1].episodes[  1]
[?] rank: 0, source_title: TheTVDB, title: "Episode 5.5 (Recap)"
[!] title: Episode 5.5 (Recap), language_rank 1, rank: 0, len(languages): "3"
[x] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Episode 5.5 (Recap)'
[=] summary                        Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB']'  Value: 'A recap of episodes 1-5 of Bakemonogatari.'
[=] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: '2016-01-08'
[=] writers                        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Nishio Ishin'
[=] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Oishi Tatsuya'
[=] producers                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Shinbou Akiyuki,Tou Fuyashi'
[x] rating                         Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: '7'
[=] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: '{'https://thetvdb.plexapp.com/banners/episodes/102261/3406651.jpg': ('TheTVDB/episodes/3406651.jpg', 1, None)}'
[x] duration                       Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB', 'AniDB']'  Value: '1500000'
[=] content_rating                 Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'TV-14'
metadata.seasons[ 1].episodes[  2]
[?] rank: 0, source_title: TheTVDB, title: "Kizumonogatari I: Iron Blood Arc"
[!] title: Kizumonogatari I: Iron Blood Arc, language_rank 1, rank: 0, len(languages): "3"
[x] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Kizumonogatari I: Iron Blood Arc'
[=] summary                        Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB']'  Value: 'I think it's about time I talked about Kiss-Shot-Acerola-Orion Heart-Under-Blade..'
[=] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: '2016-08-19'
[=] writers                        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Nishio Ishin'
[=] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Oishi Tatsuya'
[=] producers                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Shinbou Akiyuki,Tou Fuyashi'
[=] rating                         Sources:  TheTVDB, AniDB| TheTVDB, (AniDB)                             Inside: '['AniDB']'  Value: '8.44'
[=] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: '{'https://thetvdb.plexapp.com/banners/episodes/102261/4139150.jpg': ('TheTVDB/episodes/4139150.jpg', 1, None)}'
[x] duration                       Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB', 'AniDB']'  Value: '1500000'
[=] content_rating                 Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'TV-14'
metadata.seasons[ 1].episodes[  3]
[?] rank: 0, source_title: TheTVDB, title: "Tsubasa Family - Part 1"
[!] title: Tsubasa Family - Part 1, language_rank 1, rank: 0, len(languages): "3"
[x] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Tsubasa Family - Part 1'
[=] summary                        Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB']'  Value: 'Koyomi Araragi begins the day by being rudely awoken by his sister, Tsukihi. He ..'
[=] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: '2017-01-06'
[=] writers                        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Nishio Ishin'
[=] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Oishi Tatsuya'
[=] producers                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Shinbou Akiyuki,Tou Fuyashi'
[x] rating                         Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: '8.5'
[=] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: '{'https://thetvdb.plexapp.com/banners/episodes/102261/4450835.jpg': ('TheTVDB/episodes/4450835.jpg', 1, None)}'
[x] duration                       Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB', 'AniDB']'  Value: '1500000'
[=] content_rating                 Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'TV-14'
-------------------------------------------------------------------------------------------------------------------------------------------------------------
```
Actual mapping is:
```xml
  <anime anidbid="8357" tvdbid="102261" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="tt3138698,tt5084196,tt5084198">
    <name>Kizumonogatari</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-2;2-19;3-20;</mapping>
    </mapping-list>
  </anime>
```
While only this is seen:
```
[+] AniDBid:  8357, TVDBid: 102261, defaulttvdbseason:   0, offset:   0, name: Kizumonogatari
             -----          ------
              8357          102261
```

![image](https://user-images.githubusercontent.com/16750699/67613577-99cb1100-f774-11e9-92dd-e5f676924557.png)

**Comment by EndOfLine369** [comment] 2019-10-26 03:30
@ZeroQI, looks like it only processing the `anime.iter('mapping')` loop when tvdb or s2+.
So anidb entries that have any 'mapping-list' entries and happen to have a tvdb id will always pull incorrect tvdb data.

**Comment by EndOfLine369** [comment] 2019-10-26 03:39
Same issue for Hanamonogatari: Suruga Devil.
Looks like this has been an issue at the start of the redesign.
As it was always under the `if TVDBid.isdigit()`
https://github.com/ZeroQI/Hama.bundle/commit/7cad2d00b9cd044e4b250b85ce496cf9df593dc4#diff-d7b7f1f1970112645f6c605242902304R88
```
===== Scanner =====

"Hanamonogatari - Suruga Devil (TV Special)" s01e002                         "Word Search" "" "[Commie] Hanamonogatari - 02 [BD 1080p AAC] [58D7B5DC].mkv"
"Hanamonogatari - Suruga Devil (TV Special)" s01e003                         "Word Search" "" "[Commie] Hanamonogatari - 03 [BD 1080p AAC] [896DF79C].mkv"
"Hanamonogatari - Suruga Devil (TV Special)" s01e004                         "Word Search" "" "[Commie] Hanamonogatari - 04 [BD 1080p AAC] [D0C80DC9].mkv"
"Hanamonogatari - Suruga Devil (TV Special)" s01e005                         "Word Search" "" "[Commie] Hanamonogatari - 05 [BD 1080p AAC] [E57A5F43].mkv"
"Hanamonogatari - Suruga Devil (TV Special)" s01e006                         "Word Search" "" "[Commie] Hanamonogatari - 06 [BD 1080p AAC] [45EBC237].mkv"

===== HAMA =====

=== Update() ================================================================================================================================================
id: anidb-10046, title: Hanamonogatari: Suruga Devil, lang: en, force: True, movie: False
start: 2019-10-25 14:20:40,001000
=== AnimeLists.GetMetadata() ================================================================================================================================
tvdb_numbering: False
Local custom mapping file not present: anime-list-custom.xml
--- AniDBTVDBMap --------------------------------------------------------------------------------------------------------------------------------------------
[+] AniDBid: 10046, TVDBid: 102261, defaulttvdbseason:   0, offset:   0, name: Hanamonogatari: Suruga Devil
             -----          ------
             10046          102261
[ ] collection: TVDBid '102261' is part of collection: '['Bakemonogatari Collection']', related_anime_list: ['6327', '8357', '8658', '9183', '9453', '10046', '10891', '11350', '11827', '13033']
[ ] studio: 
--- return --------------------------------------------------------------------------------------------------------------------------------------------------
AniDB_id: '10046', AniDB_id2: '', AniDBid: '10046', TVDB_id: '', TVDB_id2: '102261', TVDBid: '102261'
mappingList: {
  'defaulttvdbseason': '0',
  'defaulttvdbseason_a': False,
  'episodeoffset': '0',
  'name': 'Hanamonogatari: Suruga Devil',
  'tvdbcount': 1}
AnimeLists_dict: {
  'collections': ['Bakemonogatari Collection']}

===== ScudLee =====

  <anime anidbid="10046" tvdbid="102261" defaulttvdbseason="0" episodeoffset="" tmdbid="" imdbid="">
    <name>Hanamonogatari: Suruga Devil</name>
    <mapping-list>
      <mapping anidbseason="1" tvdbseason="0">;1-10;2-10;3-11;4-12;5-13;6-14;</mapping>
    </mapping-list>
  </anime>
```

**Comment by EndOfLine369** [comment] 2019-10-26 03:55
@stevenx37, thanks for raising this. Looks like it was my recent fix to `anidb_ep()` that actually corrected the TVDB metadata pull. Which actually allowed this long existing bug to finally be seen. As had been hidden since it was broken in 2018. So it was only able to populate meta from AniDB. And would also need an AniDB series with 'mapping-list' entries so is even less likely to be seen.

**Comment by EndOfLine369** [comment] 2019-10-27 19:22
@ZeroQI, take  a look.
https://github.com/ZeroQI/Hama.bundle/compare/EOL

Should fix this isue and another issue I had seen but didn't put much thought into it but is also now fixed. Partially caused from previous simplification of defaulting `episodeoffset` to `0` to simplify the code. You can see it in the above Kizumonogatari example where technically it should not have pulled s0e1/2/3 as ScudLee has `episodeoffset=""`. So we just make sure that s1e1 is not mapped in the `mapping-list` section and if it is, don't use the series' `episodeoffset`

**Comment by ZeroQI** [comment] 2019-10-28 07:25
Will review shortly enough the code

**Comment by EndOfLine369** [comment] 2019-10-30 01:50
Looks all good to me

**Comment by EndOfLine369** [comment] 2019-10-30 01:55
@stevenx37, update your install to latest and should all be good now

**Comment by stevenx37** [comment] 2019-10-30 02:07
Nice! I think everything is working as expected, but there's this naming discrepancy with episode 1 for Hanamonogatari and Tsukimonogatari. 
![image](https://user-images.githubusercontent.com/15038615/67823166-63550500-fa98-11e9-8165-40129809a5d5.png)

**Comment by EndOfLine369** [comment] 2019-10-30 02:10
agent-update log please if you want me to look into that

**Comment by EndOfLine369** [comment] 2019-10-30 02:19
Issues in ScudLee mapping. AniDB s1e1 & s1e2 are both mapped to the same TVDB s0e10.  So no TVDB mapping is possible for s1e2. Thus you only get AniDB meta for that episode.
```
[+] AniDBid: 10046, TVDBid: 102261, defaulttvdbseason:   0, offset:   0, name: Hanamonogatari: Suruga Devil
    - season: [ 1],           [ 0], range:       [000-000], offset:   0, text: 1-10;2-10;3-11;4-12;5-13;6-14
...
  'TVDB': {'s0e10': ('1', '1', '10046'), 's0e11': ('1', '3', '10046'), 's0e12': ('1', '4', '10046'), 's0e13': ('1', '5', '10046'), 's0e14': ('1', '6', '10046'), 's-1': {'10046': '0'}},
...
metadata.seasons[ 1].episodes[  1]
[?] rank: 0, source_title: TheTVDB, title: "Suruga Devil - Part 1"
[!] title: Suruga Devil - Part 1, language_rank 1, rank: 0, len(languages): "3"
[x] title                          Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: 'Suruga Devil - Part 1'
[x] summary                        Sources: (TheTVDB), AniDB                                              Inside: '['TheTVDB', 'AniDB']'  Value: 'After the graduation of Araragi and Senjougahara, Suruga alone to deal with her ..'
[x] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['TheTVDB', 'AniDB']'  Value: '2014-08-16'
[x] writers                        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Nishio Ishin'
[x] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Itamura Tomoyuki'
[x] producers                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Tou Fuyashi,Shinbou Akiyuki'
[x] rating                         Sources:  TheTVDB, AniDB| (TheTVDB), AniDB                             Inside: '['TheTVDB', 'AniDB']'  Value: '10'
[x] thumbs                   ( 1)  Sources: (TheTVDB)                                                     Inside: '['TheTVDB']'  Value: '{'https://thetvdb.plexapp.com/banners/episodes/102261/4653123.jpg': ('TheTVDB/episodes/4653123.jpg', 1, None)}'
common.SaveFile() - CachePath: 'C:\Users\Steven Xu\AppData\Local\Plex Media Server\Plug-in Support\Data\com.plexapp.agents.hama\DataItems', file: 'TheTVDB/episodes/4653123.jpg'
[x] duration                       Sources: (TheTVDB), AniDB, MyAnimeList, TheMovieDb, OMDb               Inside: '['TheTVDB', 'AniDB']'  Value: '1500000'
[x] content_rating                 Sources: AniDB,(TheTVDB)                                               Inside: '['TheTVDB']'  Value: 'TV-14'
metadata.seasons[ 1].episodes[  2]
[?] rank: 1, source_title:   AniDB, title: "Part 1 of 5"
[=] title                          Sources:  TheTVDB, AniDB| TheTVDB, (AniDB)                             Inside: '['AniDB']'  Value: 'Part 1 of 5'
[=] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: '2014-08-16'
[=] writers                        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Nishio Ishin'
[=] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Itamura Tomoyuki'
[=] producers                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Tou Fuyashi,Shinbou Akiyuki'
[=] rating                         Sources:  TheTVDB, AniDB| TheTVDB, (AniDB)                             Inside: '['AniDB']'  Value: '5.31'
[=] duration                       Sources: TheTVDB, (AniDB), MyAnimeList, TheMovieDb, OMDb               Inside: '['AniDB']'  Value: '1500000'
....
```

Same for Tsukimonogatari. AniDB s1e1 & s1e2 are both mapped to the same TVDB s0e15.
```
[+] AniDBid: 10891, TVDBid: 102261, defaulttvdbseason:   0, offset:   0, name: Tsukimonogatari: Yotsugi Doll
    - season: [ 1],           [ 0], range:       [000-000], offset:   0, text: 1-15;2-15;3-16;4-17;5-18
...
metadata.seasons[ 1].episodes[  2]
[?] rank: 1, source_title:   AniDB, title: "Part 1 of 4"
[x] title                          Sources:  TheTVDB, AniDB| TheTVDB, (AniDB)                             Inside: '['AniDB']'  Value: 'Part 1 of 4'
[x] originally_available_at        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: '2014-12-31'
[x] writers                        Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Nishio Ishin'
[x] directors                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Itamura Tomoyuki'
[x] producers                      Sources: (AniDB),TheTVDB                                               Inside: '['AniDB']'  Value: 'Tou Fuyashi,Shinbou Akiyuki'
[x] rating                         Sources:  TheTVDB, AniDB| TheTVDB, (AniDB)                             Inside: '['AniDB']'  Value: '6.23'
[x] duration                       Sources: TheTVDB, (AniDB), MyAnimeList, TheMovieDb, OMDb               Inside: '['AniDB']'  Value: '1500000'
...
```

**Comment by stevenx37** [comment] 2019-10-30 02:30
Oh, can you check [Bakemonogatari](https://anidb.net/anime/6327) ([TVDB](https://www.thetvdb.com/series/monogatari/seasons/1)) too:
![image](https://user-images.githubusercontent.com/15038615/67823839-ff800b80-fa9a-11e9-9453-5077b14a286d.png)
[Bakemonogatari.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/3786646/Bakemonogatari.agent-update.log)
Alright, that's okay with me.

**Comment by EndOfLine369** [comment] 2019-10-30 02:57
And the issue with this one is?

**Closed** 2019-10-30 06:23 UTC
Labels: bug
