### ISSUE TITLE
Digimon Ghost Game refuses to be matched to it's metadata

### ISSUE THREAD

**Issue by jibarofoss** [ZeroQI/Hama.bundle#542] opened 2023-02-26 23:30 UTC
Today I noticed that the series entry for Digimon Ghost Game hadn't updated for the last 5 episodes. After updating Hama.bundle and Absolute Series Scanner to no avail, I tried building a new library, except it refuses to fetch any metadata at all there. I tried unmatching and rematching on the old library, moving and then placing back the files, still no dice. Any advise on how to proceed?
Logs (couldn't find filelist or scanner logs, no logs at all on com.plexapp.agents.hama/DataItems/_Logs for the new library)
[com.plexapp.agents.hama.log](https://github.com/ZeroQI/Hama.bundle/files/10834993/com.plexapp.agents.hama.log) 
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/10834995/com.plexapp.system.log)
[Digimon Ghost Game.agent-search.log](https://github.com/ZeroQI/Hama.bundle/files/10834999/Digimon.Ghost.Game.agent-search.log) (from the original library)
[Digimon Ghost Game.agent-update.log](https://github.com/ZeroQI/Hama.bundle/files/10835000/Digimon.Ghost.Game.agent-update.log) (from the original library)

**Comment by jibarofoss** [comment] 2023-02-26 23:33
This screenshot shows the series after manual matching, nothing ever happens to it no matter how many times I hit refresh metadata or scan library
![Screenshot_20230226_193253](https://user-images.githubusercontent.com/5615573/221444174-04cabcbb-cff1-416d-a131-2a67d7db01e4.png)

**Comment by ZeroQI** [comment] 2023-02-26 23:48
Original library update.log show correct logs, no errors, so possibly a Plex corrupted database issue

Search and update logs for new library would have been nice... Seem like metadata fails since some time which hints at a Plex issue.

**Comment by jibarofoss** [comment] 2023-02-26 23:52
Unfortunately there aren't any search and update logs on the new library, it's been on the metadata spinny symbol for hours, the scanner refuses to touch it

**Comment by ZeroQI** [comment] 2023-02-26 23:55
Try fix for corrupted plex database first I would say, reinstall plex fully second.
If there's no agent logs it fails before launching it so plex issue...

**Comment by jibarofoss** [comment] 2023-02-27 00:08
Does a corrupted db affect a specific series only? Everything else is populating just fine on the new library.

**Comment by ZeroQI** [comment] 2023-02-27 00:11
It could to be honest
Scanner ran but search and/or update didn't run. 
Without logs tricky to tell... Check system.log for errors if no series log or errors in hama log

**Comment by jibarofoss** [comment] 2023-02-27 01:01
Would this root agent log be of any help?  I'm seeing some errors related to Digimon Ghost Game there.
[_root_.agent.log](https://github.com/ZeroQI/Hama.bundle/files/10835280/_root_.agent.log)

**Comment by jibarofoss** [comment] 2023-02-27 01:23
Think I found the culprit on the system log.
[com.plexapp.system.log](https://github.com/ZeroQI/Hama.bundle/files/10835329/com.plexapp.system.log)

**Comment by ZeroQI** [comment] 2023-04-23 12:49
Duplicate of https://github.com/ZeroQI/Hama.bundle/issues/547

**Closed by ZeroQI** 2023-04-23 12:49 UTC
