### ISSUE TITLE
Media with a UNC path loads no metadata

### ISSUE THREAD

**Issue by natyusha** [ZeroQI/Hama.bundle#420] opened 2020-09-21 08:34 UTC
Hi, I've recently set up ASS + Hama for a large anime library and it has worked very well however any files that I try to add via a UNC path such as `//natyusha/test` fail to load any metadata. In order to make sure there were no permission/scanner issues I created two new test libraries using ASS as the scanner with one using HamaTV and the other using TheTVDB. Both test libraries referenced the same UNC path which contained the series "Bacanno!" in its own folder. Only the library using TheTVDB agent was successful in loading any metadata.

![firefox_2020-09-21_04-18-24](https://user-images.githubusercontent.com/985941/93745684-ece65780-fbc1-11ea-8297-5c910bfb22da.png)
![firefox_2020-09-21_04-18-05](https://user-images.githubusercontent.com/985941/93745672-e8ba3a00-fbc1-11ea-8599-76ff470fb7d6.png)

After looking at the logs the following seems to be the most relevant error ([full logs here](https://github.com/ZeroQI/Hama.bundle/files/5254228/test.logs.zip)):

```
2020-09-21 04:26:30,341 (3720) :  ERROR (networking:196) - Error opening URL 'http://127.0.0.1:32400/:/plugins/com.plexapp.agents.hama/messaging/function/X0FnZW50S2l0OlVwZGF0ZU1ldGFkYXRh/Y2VyZWFsMQoxCmxpc3QKMApyMAo_/Y2VyZWFsMQoxCmRpY3QKMTAKczIKZW5zNApsYW5nYjFzNQpmb3JjZWIwczgKcGVyaW9kaWNzNQo5NTY3NXM0CmRiaWRpMApzNwp2ZXJzaW9ubnMxMApwYXJlbnRHVUlEbnM4CnBhcmVudElEczcKVFZfU2hvd3MxMAptZWRpYV90eXBlczQ0CmNvbS5wbGV4YXBwLmFnZW50cy5oYW1hOi8vYW5pZGItNDg5Nz9sYW5nPWVuczQKZ3VpZHMxMAphbmlkYi00ODk3czIKaWRyMAo_'
2020-09-21 04:26:30,364 (3720) :  CRITICAL (core:579) - Exception in update for com.plexapp.agents.hama://anidb-4897?lang=en (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-a78fef9a9\System.bundle\Contents\Code\agentservice.py", line 510, in update_task
    agent_id = item_els[0].get('id')
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-a78fef9a9\System.bundle\Contents\Code\agentservice.py", line 1292, in agent_update_metadata
    kwargs=kwargs
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-a78fef9a9\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\messaging.py", line 86, in call_external_function
    packed_result = self._core.networking.http_request(url, cacheTime=0, timeout=None, immediate=True).content
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-a78fef9a9\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 346, in http_request
    return HTTPRequest(self._core, url, data, h, url_cache, encoding, errors, timeout, immediate, sleep, opener, follow_redirects, method)
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-a78fef9a9\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 118, in __init__
    self.load()
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-a78fef9a9\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\components\networking.py", line 158, in load
    f = self._opener.open(req, timeout=self._timeout)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 435, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Plex\Plex Media Server\python27.zip\urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 500: Internal Server Error
```

**Comment by ZeroQI** [comment] 2020-09-21 10:18
None of the python files mentioned point to my agent, making it very difficult to troubleshoot
Both series resent (Akira, Bakano) gives this log at the end which is done in https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/AnimeLists.py line 87
```
=== AnimeLists.GetMetadata() ================================================================================================================================
tvdb_numbering: False
```

it is hightly possible GetAniDBTVDBMapCustom (line 46-60) is not equipped for UNC path, and gets stuck in an infinite loop

[ ] library:    "test"
[ ] root:       "\\natyusha\test"
[ ] path:       "Akira"       [!] file:       "\\natyusha\test\Akira\Akira.mkv"
[ ] path:       "Baccano!" [!] file:       "\\natyusha\test\Baccano!\Baccano! - 11.avi"

**Comment by natyusha** [comment] 2020-09-21 22:24
Hey, thanks for the quick response. After some quick testing I can confirm that the following commit is what broke UNC paths: 

https://github.com/ZeroQI/Hama.bundle/commit/9dda1cddd88bfdc9a95d35073b0ba5c892de2047#diff-d7b7f1f1970112645f6c605242902304

I changed those two lines back in my AnimeLists.py and am able to import to my test library now.

**Comment by ZeroQI** [comment] 2020-09-22 11:31
That helps tremendously, thank you.

We solved a loop for one user just to create one with another, so that might need to clever coding to avoid both
- we mustn't go below root level
- we need to avoid loops (dir being identical durign iterations)

I might be able to reproduce the behaviour of the old code with the limitations added, here is what i would try:
```
  AniDBTVDBMapCustom = None
  lib, root, path = common.GetLibraryRootPath(common.GetMediaDir(media, movie))
  dir = os.path.join(root, path)
  while dir:  #while dir and os.path.splitdrive(dir)[1] != os.sep:
    scudlee_filename_custom = os.path.join(dir, SCHUDLEE_CUSTOM)
    if os.path.exists( scudlee_filename_custom ):
      try:
        AniDBTVDBMapCustom = XML.ElementFromString(Core.storage.load(scudlee_filename_custom))
        Log.Info("Local custom mapping file loaded: {}".format(scudlee_filename_custom))
      except:  Log.Error("Failed to open: '%s', error: '%s'" % (scudlee_filename_custom, e))
      else:    break
    dir = os.path.dirname(dir) if len(dir) > len(root) and os.path.dirname(dir) != dir and os.path.splitdrive(dir)[1] != os.sep else ''
  else:  Log.Info("Local custom mapping file not present: {}".format(SCHUDLEE_CUSTOM))
  return AniDBTVDBMapCustom
```
If this work, then i can add it to the master, but am not in a position to test currently

**Comment by natyusha** [comment] 2020-09-23 06:10
As far as I can tell the above GetAniDBTVDBMapCustom() works for my UNC path based test library as well as my other regular libraries without any issue. I never encountered the loop that the other user required though so I can't speak to that.

**Comment by EndOfLine369** [comment] 2020-12-04 06:18
Hi @natyusha,
Can you please revert to the original function and update to below which added a single "Log.Info" line to print the strings and seen length since that is all the test `len(dir) > len(root)` is doing that is keeping you stuck in the loop and let us know the log up to where it starts repeating.
````python
def GetAniDBTVDBMapCustom(media, movie):  
  AniDBTVDBMapCustom = None
  lib, root, path = common.GetLibraryRootPath(common.GetMediaDir(media, movie))
  dir = os.path.join(root, path)
  while dir:
    Log.Info("Checking: root: '{}' ({}), dir: '{}' ({})".format(root, len(root), dir, len(dir)))   ##### HERE ######
    scudlee_filename_custom = os.path.join(dir, SCHUDLEE_CUSTOM)
    if os.path.exists( scudlee_filename_custom ):
      try:
        AniDBTVDBMapCustom = XML.ElementFromString(Core.storage.load(scudlee_filename_custom))
        Log.Info("Local custom mapping file loaded: {}".format(scudlee_filename_custom))
      except:  Log.Error("Failed to open: '%s', error: '%s'" % (scudlee_filename_custom, e))
      else:    break
    dir = os.path.dirname(dir) if len(dir) > len(root) else ''  # Clear variable if we've just finished processing down to (and including) root
  else:  Log.Info("Local custom mapping file not present: {}".format(SCHUDLEE_CUSTOM))
  return AniDBTVDBMapCustom
```

**Comment by ZeroQI** [comment] 2021-01-18 19:44
@natyusha ?

**Comment by ZeroQI** [comment] 2021-01-19 13:01
@natyusha ?

**Comment by natyusha** [comment] 2021-01-19 15:57
Sorry, I thought that this was already resolved when I replied to https://github.com/ZeroQI/Hama.bundle/issues/420#issuecomment-696663490 saying that it worked fine (totally missed https://github.com/ZeroQI/Hama.bundle/issues/420#issuecomment-738590702 two months later from EndOfLine369 too).

In any case, I currently don't have access to that Plex setup so I'm not able to test anything at this time. I'm stuck waiting on some computer components to arrive that seem to have no availability or set shipping date.

**Comment by natyusha** [comment] 2021-02-01 04:38
Got Plex up and running again and made a test library with UNC paths like in the first post and I'm not able to reproduce the same looping as before while using the GetAniDBTVDBMapCustom with the extra logging from https://github.com/ZeroQI/Hama.bundle/issues/420#issuecomment-738590702. It may have been an issue with Plex media server itself that was fixed since then.

The following from the pms changelog is a possibility: 
[(Library) Certain assets using UNC paths would not always work (#11931)](https://forums.plex.tv/t/plex-media-server/30447/374)

**Comment by ZeroQI** [comment] 2021-02-12 14:04
Thanks for the reply, it is nteresting to know.
If the code was at fault, it should be reproductible, so i am going to close this, we can always reopen it if needed.

**Closed by ZeroQI** 2021-02-12 14:04 UTC
Labels: bug
