### ISSUE TITLE
Poster issue

### ISSUE THREAD

**Issue by iCrawl** [ZeroQI/Hama.bundle#349] opened 2019-10-02 22:24 UTC
Hey,

A new anime season is rolling around the corner, so I thought updating the whole Hama stack was necessary again as I couldn't see any posters for the new titles that released, as of today, today.

![image](https://user-images.githubusercontent.com/20760160/66086231-b314df00-e573-11e9-8645-bb3545632326.png)

Metadata is getting applied just fine
![image](https://user-images.githubusercontent.com/20760160/66086250-c3c55500-e573-11e9-9154-5198238c0adf.png)

I had that issue once already in the past, but I can't really remember how I fixed it. 
I have been over recreating this tiny library (luckily its only one with less than 10 anime in it for now), restarting plex and the server.

Here is the log of the shown above file:
[anime.log](https://github.com/ZeroQI/Hama.bundle/files/3683622/anime.log)

And here the hama log after running `refresh metadata`
[hama.log](https://github.com/ZeroQI/Hama.bundle/files/3683625/hama.log)

If any more info is needed let me know.

**Comment by ZeroQI** [comment] 2019-10-02 22:46
'http://img7.anidb.net/pics/anime/237687.jpg': ('AniDB/poster/237687.jpg', 1, 'http://img7.anidb.net/pics/anime/thumbs/150/237687.jpg-thumb.jpg')}
    meta_old: [
      ]
[x] posters                  ( 1)  Sources: (AniDB), tvdb4, TheTVDB, TheMovieDb, FanartTV                 Inside: '['AniDB']'  Value: '{'http://img7.anidb.net/pics/anime/237687.jpg': ('AniDB/poster/237687.jpg', 1, 'http://img7.anidb.net/pics/anime/thumbs/150/237687.jpg-thumb.jpg')}'
common.metadata_download() - Exception: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>, url: 'http://img7.anidb.net/pics/anime/237687.jpg', filename: 'AniDB/poster/237687.jpg'

Duplicate of open bug https://github.com/ZeroQI/Hama.bundle/issues/194 so closing this one.
Linux impacted, windows plex server ok.

**Closed by ZeroQI** 2019-10-02 22:46 UTC

**Comment by iCrawl** [comment] 2019-10-02 22:54
Ah, I was looking at it and wasn't entirely sure if it matches up. Thanks for the confirmation, ill keep watching how the other issue progresses then!
